### ISSUE TITLE
Copy Change for Donation Sprint Template

### ISSUE THREAD

**Issue by mrkimani-ndegwa** [350org/ak_intl_v3#237]
Hi Friends! 350 has a new mailing address, and I’d like to change the template on the V3 sprint donation pages to where it says “donate by check”
Here’s our new address:
350.org
PO Box 843004
Boston, MA 02284-3004
Who would be able to help with this? Thank you!

**Comment by rachelhbd** [comment]
This was resolved! We edited it in the language strings
