### ISSUE TITLE
Tweet preview is only visible for custom tweets; should also be visible for default tweets

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#329]
**Context**
On this signup page (https://act.350.org/thanks/stopeacop-marche/), the tweet text is not showing up in the preview box.

<img width="525" alt="Screenshot 2022-05-25 at 22 15 02" src="https://user-images.githubusercontent.com/22962348/170380635-e1c5c75a-6fce-4410-9bdf-1cebc529aee6.png">

AK advised that this is because it doesn't have a custom twitter share message set and one doesn't. It *looks* like the page has a twitter message set here: https://act.350.org/admin/core/pagefollowup/6148/change/?page=15038

<img width="801" alt="Screenshot 2022-05-25 at 23 34 31" src="https://user-images.githubusercontent.com/22962348/170380712-1676cfcf-fb1e-42ce-8fa8-1d9ad8933ca8.png">

but that's actually showing the auto-generated message that will be used by AK's sharing system if we *don't* set one. And AK say _"in your template you're doing something unusual - you're accessing the field that holds the customized twitter message directly - which will only work if the page has one set. The quickest workaround here is to edit that page's twitter message. You'll need to make some change so the system knows it needs to store it, just clicking and saving won't do the trick. The longer-term fix here is to have some logic in your template to show the default message (which is just the page's title + URL) in case a custom message wasn't set."_

The same problem doesn't exist on this example petition, because the share text has been customised: https://act.350.org/thanks/rachel-petition-testing/ 

It would be good to implement the longer-term fix AK are suggesting, to avoid user confusion

**Dev needs**

- [ ] In thanks.html https://github.com/350org/ak_intl_v3/blob/3b508974efb705c9f720bdd05e413b757b7ad0d5/thanks.html#L267, add conditionals so that if {{ page.followup.twitter_message }} isn't present, the viewer will see the page title + URL

**Acceptance criteria** 

- [x] On an AK thanks page such as https://act.350.org/thanks/stopeacop-marche/, if the tweet text hasn't been customised, the tweet preview is not blank and shows the page title and url

**Comment by michaelsnook** [comment]
I can't tell (without access to the AK admin) how to confirm exactly which templates and data points this page is being built by. Is there a separate template for French language? how does that work? Whoever picks up this ticket, if you're not _already_ familiar with the multilingual features in this AK templateset, make sure you poke around first to make sure you're making changes in the right places.

(Also, while you're there, please note and fix this typo: `"href="` in that "Tweetez" section, which might cause some browsers to parse either the link or the element's styles incorrectly.)

**Comment by rachelhbd** [comment]
@sukhada thanks, this looks good!

I updated this page to use the bugfixes template (https://act.350.org/thanks/stopeacop-marche/) and seeing the tweet preview as expected:
![Image](https://user-images.githubusercontent.com/22962348/174868981-546e9319-4419-4445-a7b7-5cebeffe9d2c.png)

**Comment by rachelhbd** [comment]
Likewise in v3 after merging in, preview is looking good - closing! 😃
