### ISSUE TITLE
Ability to hide a custom action field for AB tests


### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#331]
This was a request from JuliaO: https://gitlab.com/350/team-projects/-/issues/248
After some scoping, we should be able to support this with some custom code in a custom page field, so no need for dev work:
https://docs.google.com/document/d/1vcquCxxxY_mYkqotO6UNvJ-ZFRle2PKKczXN3uHVMH4/edit#heading=h.4zm3gmqyqehv

**Comment by michaelsnook** [comment]
yes, exactly! (sry just going through old notifications)
