### ISSUE TITLE
Unsubscribe page: Make survey multilingual; add language strings to template

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#339]
Part of Unsubscribe page epic https://github.com/orgs/350org/projects/8/views/1

**Context** 
We set up our templates to be translatable by making sure every piece of text is enclosed in a language filter tag, so we can add translations in the language strings (https://act.350.org/admin/core/language/) without requiring further dev work. Ideally there should be no front-end text that isn't editable on the AK admin page, or enclosed in a language string!

New language strings waiting for translation are recorded here: https://docs.google.com/spreadsheets/d/1L4o11Q894YjOX6ipR5jyoleDrt0uBpZHWMZpTLCpqx8/edit#gid=0

Jamie had added quite a few but I founds some that weren't included, and also some possibly more complex issues:

### "Before you go survey"

- [x] For "I'm no longer interested in 350.org's campaigns" (reason 4) and "Other" (reason 5), there is some Javascript which appears to be dependent on the English language content - is there a way to make this work multilingually?
https://github.com/350org/ak_intl_v3/blob/a02514e0b5334525e75aac7acaebbcfa6ef79eb0/unsubscribe.html#L432
This feature opens up a "Can you tell us more?" box when "Other" or "No longer interested..." is selected in the survey options:
https://act.350.org/unsubscribe/fa-sprint-unsubscribe-redesign/?akid=.3782060.9RBSU7

![Image](https://user-images.githubusercontent.com/22962348/170728970-cee82555-4473-49b8-86da-8929d2fbb9f9.png)

- [x] If this is workable with ^^ also want to add language filters tags to the survey choices 1-5: https://github.com/350org/ak_intl_v3/blob/a02514e0b5334525e75aac7acaebbcfa6ef79eb0/unsubscribe.html#L393
Suggested filter names [added to translations doc](https://docs.google.com/spreadsheets/d/1L4o11Q894YjOX6ipR5jyoleDrt0uBpZHWMZpTLCpqx8/edit#gid=0):

```
unsubscribe_reason_frequency
unsubscribe_reason_consent
unsubscribe_reason_difemail
unsubscribe_reason_campaigns
unsubscribe_reason_other
```

- [x] Note on the language filter tags for the survey choices - I can see the EN labels have a space in front of them in the code. This will get lost in the language string translation so would be good to position the filter tag after the spaces here to avoid the translated versions getting misaligned

![Image](https://user-images.githubusercontent.com/22962348/170727388-85e633cf-d4bf-40bb-a992-495e1429818d.png)

- [x] "Can you tell us more?" text ([L410](https://github.com/350org/ak_intl_v3/blob/a02514e0b5334525e75aac7acaebbcfa6ef79eb0/unsubscribe.html#L410) also needs a language filter if possible - suggest `unsubscribe_reason_other_placeholder`

### Mailing list names (update: won't do)
Is it feasible to add language string filtering for mailing list names? https://github.com/350org/ak_intl_v3/blob/a02514e0b5334525e75aac7acaebbcfa6ef79eb0/unsubscribe.html#L380
Language string label could be: `unsubscribe_list_1_name`

This is more of a nice to have, as really it's a feature AK should fix imo.
Using language strings in the list names themselves https://act.350.org/admin/core/list/ is not supported

### Simple lang string additions
- [x] Replace "Unsubscribe from all" text with version contained in language string `{% filter ak_text:"unsubscribe_from_all_label" %}Unsubscribe from all{% endfilter %}`
(I've added `unsubscribe_from_all_label` to the [list of lang strings for translation](https://docs.google.com/spreadsheets/d/1L4o11Q894YjOX6ipR5jyoleDrt0uBpZHWMZpTLCpqx8/edit#gid=0))
Should be here in the code: https://github.com/350org/ak_intl_v3/blob/a02514e0b5334525e75aac7acaebbcfa6ef79eb0/unsubscribe.html#L418

- [ ] If you spot any other unfiltered text, please can you let me know/document here?

**Comment by rachelhbd** [comment]
This ticket grew a bit! Is it helpful to break out the 3 sections into different tickets?

**Comment by sukhada** [comment]
@rachelhbd I had a question about this task:
>  Is it feasible to add language string filtering for mailing list names?

Do you mean that you want translations for mailing list names? If so, won't these be dynamic? Meaning that we can't use language filters to set them?

**Comment by rachelhbd** [comment]
Yes, they are dynamic indeed! I guess I was wondering if there was some kind of logic we could use to see what the dynamic input is and _then_ translate it, but as I type that out I realise that's probably not feasible. Which is okay! I could make a feature request to AK that mailing list names should support translations

**Comment by rachelhbd** [comment]
Thanks @sukhada! Linking the relevant bit of the PR here: https://github.com/350org/ak_intl_v3/pull/351/commits/8e14f0df48254d8382018b18b9b9ca9bfd80a897

We don't have all the strings translated yet, but I added a test language string for the "Other" option -> "Other (fr) 
https://act.350.org/unsubscribe/unsubscribe-fr/?akid=.3782060.9RBSU7&template_set=350.org%20-%20International%20v3%20(With%20the%20Ranks%20Unsubscribe%20Page)
and this looks to be working fine
