### ISSUE TITLE
Unsubscribe page: User sees alternative unsub page in correct language

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#340]
Part of Unsubscribe page epic https://github.com/orgs/350org/projects/8/views/1

**As a user unsubscribing in another language, I would like to see the alternative unsubscribe page in my own language**

Related to https://github.com/350org/ak_intl_v3/issues/339

**Context**
When seeing the unsubscribe page as a recognised user, viewers will see a link to an alternative form that won't recognise them eg: https://act.350.org/unsubscribe/fa-sprint-unsubscribe-redesign/?akid=.3199019.2YIX0L

![Image](https://user-images.githubusercontent.com/22962348/170736266-3870a9a5-b809-4d56-a2bb-746ffb721a4c.png)

The "Use this form instead" url currently points to the EN language version of the page.

There might be a few ways to solve this

- Could we [add a language string here](https://github.com/350org/ak_intl_v3/blob/69e818027a216963741721fbc1fcca61ff055866/unsubscribe.html#L368) to replace the `<a href="/unsubscribe/unsubscribe">` link with a customised link per language?
- could we use naming conventions or url parameters?
- A string of conditionals

We should be able to keep the current urls of [our unsubscribe pages in different languages](https://act.350.org/admin/core/page/?o=-3&type__exact=Unsubscribe) - they mostly have a naming convention of "unsubscribe-[Language code]", but there is a bit of variation which we could fix if it's helpful

**Comment by sukhada** [comment]
@rachelhbd I think the best way to handle this is a string of conditionals, because we don't have unsubscribe pages for all the different regions that folks could be from. One flag is that the "UK" unsubscribe page seems to be in Russian: https://act.350.org/admin/core/unsubscribepage/10679/change/.

**Comment by rachelhbd** [comment]
This is working for me! eg. the French page links through to https://act.350.org/unsubscribe/unsubscribe-fr now:
https://act.350.org/unsubscribe/unsubscribe-fr/?akid=.3199019.2YIX0L&template_set=350.org%20-%20International%20v3%20(With%20the%20Ranks%20Unsubscribe%20Page)

**Comment by rachelhbd** [comment]
Noting for myself that we might need to add more unsubscribe pages in future but we currently have
- DE, FR, ES, PT, JP, TR, SE, NL, PL. 

We may want to add Chinese, Bengali later but would need to translate the whole pages first.

![Image](https://user-images.githubusercontent.com/22962348/175044616-17a85dc0-8131-47eb-9443-faf8300ecd71.png)

**Comment by rachelhbd** [comment]
Actually sorry - realising we do have a few more translations linked from the multilingual menu here: https://act.350.org/unsubscribe/unsubscribe-swahili/

I'll come back to this later this week and double check exactly which ones we want to include

**Comment by rachelhbd** [comment]
Hey @sukhada, ok I got round to checking this - please could we add these 3 below?

language_name_id | user_count | unsub url | lang code
-- | -- | -- |--
English (1) | 630,508 | ✔️
Français (6) | 39,568 | ✔️
Nederlands (14) | 13,167 | ✔️
Português (2) | 12,097 | ✔️
日本語 (Japanese/Nihongo) (7) | 11,393 | ✔️
Español (3) | 7,021 | ✔️
Deutsch (8) | 4,993 | ✔️
Türkçe (23) | 2,097 | ✔️
Bahasa Indonesia (24) | 2,009 | **https://act.350.org/act/unsubscribe-bahasaindonesia/** | id
Bengali (34) | 799 | **https://act.350.org/act/unsubscribe_bn/** | bn
None | 267 | ✔️
中文 (Chinese trad) (9) | 151 | **https://act.350.org/act/unsubscribe-chinese/** | zh
Korean (30) | 1
Русский (5) | 1
Italiano (4) | 1

**Comment by sukhada** [comment]
@rachelhbd updated all of these, also added Korean, Russian, and Italian to follow the same naming convention. I also updated Arabic to follow a similar naming convention:

| language_name_id  | unsub url | lang code |
| ------------- | ------------- | ------------- |
| Korean  | /unsubscribe/unsubscribe-ko  | ko |
| Русский  | /unsubscribe/unsubscribe-ru  | ru |
| Italian  | /unsubscribe/unsubscribe-it  | it |
| Arabic  | /unsubscribe/unsubscribe-ar  | ar |

**Comment by rachelhbd** [comment]
Thanks Sukhada! Ooh actually we won't want those four (Korean through to Arabic) as we aren't going to translate the new unsubscribe page into those languages - they are historic for us and we're not recruiting in them - it would be better for those folks to see the English version so we don't risk broken links

**Comment by sukhada** [comment]
@rachelhbd Gotcha! Do we only want to include the languages in the table you listed? For example, I think we have a link to Swahili and Polish pages, which don't seem to be in your list. If not, I can go ahead and remove these additional links.
