### ISSUE TITLE
Unsubscribe page: Increase visibility of checkbox and radio boxes, submit buttons and links

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#343]
On the new unsubscribe page eg. https://act.350.org/unsubscribe/fa-sprint-unsubscribe-redesign?akid=.4350316.DJLspN, there are a few visibility/readability issues:

- the unchecked checkboxes are hard to see, can we put an outline around them or darken the background colour?
- the unchecked radio buttons are also hard to see, can we put an outline around these too?

![Image](https://user-images.githubusercontent.com/22962348/172738985-57263473-f9fe-475e-9de5-28c584f510ef.png)

- the "Unsubscribe from all" link is also too small to be readable, can it be the same font size/weight as "Before you go, please tell us why"?
- the "Unsubscribe from selected" button is also a bit more cluttered with the additional text (previously it just said "Unsubscribe"). Not sure the best approach here - perhaps both a wider button and smaller text?

**Comment by sukhada** [comment]
@rachelhbd Would a good solution to this problem:
> the "Unsubscribe from selected" button is also a bit more cluttered with the additional text (previously it just said "Unsubscribe"). Not sure the best approach here - perhaps both a wider button and smaller text?

be to just go back to "Unsubscribe" instead of "Unsubscribe from selected"?

**Comment by sukhada** [comment]
actually nevermind, I see the next issue tackles how to handle this in more detail!

**Comment by rachelhbd** [comment]
@sukhada right - I think just we want the UX to be clear that the button unsubscribes from the selected lists only. I guess it is possible that just "Unsubscribe" + "Unsubscribe from all" options _might_ be clear enough for the user - let me know if you think that's the case after digesting the other ticket as well!
