### ISSUE TITLE
Unsubscribe page: Ability to preselect a single list, if user is subscribed to multiple

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#344]
In the Unsubscribe page, we'd ideally like to be able to preselect the mailing list the user arrived on the page from, so they are prompted to only unsubscribe from _one_ mailing list they weren't getting on with the content from, rather than all lists! This means supporters can choose to stay in touch on issues that interest them rather than unsubbing completely

ActionKit okay'd this approach, as long as we have a prominent "Unsubscribe from all" link on the page.
AK docs: https://act.350.org/docs/manual/sidebar/page_unsubscribe.html?#unsubscribe-pages

We have specific mailing wrappers for each list, meaning we could either:
- have a different link in the wrapper that either went to a specific version of the unsubscribe page. Jamie who did the dev work on this before suggested "Have an unique unsubscribe page copy for a given mailing wrapper. We'd then want to change the intro copy, and add some JS to a HTML custom field which would preselect a specific list to unsubscribe from (the list which is preselected would be hardcoded/not dynamic)"
- preselect the list via a url parameter, if possible

We talked about this with Jamie, but I don't think we landed on a working solution yet.

This mainly relevant for mailing lists 1 and 62, but would ideally be replicable for multiple partner campaign lists as well.

**Comment by sukhada** [comment]
@rachelhbd I've implemented this using a url parameter called `mailing_list_id` which should be passed through via the unsubscribe link in the mailing wrapper. Since you mentioned that we have specific mailing wrappers for each list, all we will have to do is to update the link to be `https://act.350.org/unsubscribe/unsubscribe/**?mailing_list_id=1**`, with the appropriate mailing list ID added to each mailing wrapper.

**Comment by rachelhbd** [comment]
Ah that's ideal, thanks so much!

**Comment by rachelhbd** [comment]
Just confirming it works for me! Here was a demo page

![Image](https://user-images.githubusercontent.com/22962348/175046857-b56cf888-6c96-4807-a480-ad437b759d60.png)
 
https://act.350.org/unsubscribe/fa-sprint-unsubscribe-redesign?template_set=350.org%20-%20International%20v3%20(With%20the%20Ranks%20Unsubscribe%20Page)&akid=.4350316.DJLspN&mailing_list_id=55

And it unsubscribed this user from the "Test list" as intended 😁 

![Image](https://user-images.githubusercontent.com/22962348/175047014-18d97584-e499-4d7a-bd1b-9a6d87c089e3.png)
