### ISSUE TITLE
Unsubscribe page: User sees "Unsubscribe from selected" button when signed up to multiple lists

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#345]
As in this issue https://github.com/orgs/350org/projects/8/views/5, we have different logic for whether users are signed up to one or multiple lists.

At the moment, everyone just sees an "Unsubscribe" button as the main blue button, alongside "Unsubscribe from all" text link if multiple lists are present. The button text is set in the "unsubscribe_submit_button" language string.

Can the button text change to "Unsubscribe from selected" if the user is subscribed to multiple lists? I could add another language string such as unsubscribe_submit_button_multiple for this logic if useful?

I previewed this by using the submit button text custom page field to override the default text, and I think the button will also need to be wider and the text a bit smaller to accommodate the additional text

**Comment by sukhada** [comment]
@rachelhbd currently it looks like `unsubscribe_submit_button` is set to Unsubscribe from selected (based on the code). We could change this so that `unsubscribe_submit_button_multiple` is set to Unsubscribe from selected, and `unsubscribe_submit_button` is just set to Unsubscribe.

**Comment by rachelhbd** [comment]
Sorry, I think I wasn't very clear on this- let me come back with an example here!
