### ISSUE TITLE
Sign > share > donate flow: can't submit form in Safari when content blockers are enabled

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#346]
### Context
See https://github.com/orgs/350org/projects/8/views/7 for more background on the Sign > share > donate flow

### Bug
When loading a page using the Sign > share > donate flow in Safari/chrome, it seems that content blockers can cause the submit button to fail to move to the next step silently, and we just see the "loading" icon spinning forever....

https://act.350.org/sign/stop-jackdaw-gas-field-uk/
https://act.350.org/sign/custom_page_field_demo_petition/

![Image](https://user-images.githubusercontent.com/22962348/172747100-f9323fb1-c5a8-442b-8f11-ad008b0f548f.png)

When I go to the Safari menu > view > "load page without content blockers" the page works correctly.

I think (but not 100% sure) these content blockers are default safari behaviour rather than due to an extension, but can also be switched off in Safari > Preference > websites > content blockers. If it is default behaviour it could be affecting a good chunk of users (although this flow is not being used by many live pages)

I haven't found the same issue using privacy extensions in Chrome.

The "loading" beach ball icon on the submit button is a bit of JS I think designed to keep people on the page when there is a lag or delay with the next step loading, since this after-action feature can be a bit slow for users on slow connections. 

### Fix

The main goal of this bugfix is to allow users using Safari with content blockers to submit their action and see the next step (currently a share ask). I don't mind how we do it!

One option is to remove the loading wheel and instead look at other ways to speed up the page. Or if we keep it, can we make it non-critical for the flow if scripts are blocked, or show a notice to warn users who have content blockers enabled?

**Comment by sukhada** [comment]
@rachelhbd I was able to reproduce this on Chrome using an adblocker, but not having luck reproducing on Safari. Could you tell me the version of Safari you're seeing this on?

**Comment by rachelhbd** [comment]
@sukhada thank you, confirming that both these pages using the Bugfix templates are working for me in Safari!

https://act.350.org/sign/custom_page_field_demo_petition/?template_set=350.org%20-%20International%20v3%20(With%20the%20Ranks%20Bug%20Fixes)

https://act.350.org/sign/stop-jackdaw-gas-field-uk/?template_set=350.org%20-%20International%20v3%20(With%20the%20Ranks%20Bug%20Fixes)

**Comment by rachelhbd** [comment]
Looking all good in v3 as well! https://act.350.org/sign/stop-jackdaw-gas-field-uk/
