### ISSUE TITLE
Progress meter on action pages shows combined total number from multilingual campaign

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#347]
### Context
We frequently use AK's multilingual campaigns feature to tie together multiple versions of a petition or action page https://act.350.org/admin/core/multilingualcampaign/ 
We use it both for actual multiple campaigns, as well as to tie together same-language copies of pages that have been customised for ads, SMS or regional customisation

We have also tested adding a progress meter to action pages and found that it tends to increase action rates (social proof!)
![Image](https://user-images.githubusercontent.com/22962348/172873295-ee6f6aa9-3548-4818-8ded-dba977c9a291.png)

The progress meter has various features that are controlled with custom page fields, such as adding a "starting value" for the total action count (allowing us to add offline or partner signature numbers), and a target number of actions that increases as more actions are taken.

The code for this is here: https://github.com/350org/ak_intl_v3/blob/develop/progress_meter.html

And here's an example multilingual campaign using the progress meter on some pages:
https://act.350.org/admin/core/multilingualcampaign/282/overview/

Notes for QA: it can sometimes take 5-10 minutes for progress meter numbers to update until after actions have been taken. The progress meter will also be hidden unless a goal is set and the number of actions is above the threshold if one has been set in a custom page field:

![Image](https://user-images.githubusercontent.com/22962348/172878194-68968317-61dc-41a4-89a4-e98859688e3c.png)

### Issues
- The progress meter is showing total actions taken. We have been seeing a number of users taking multiple actions on different page versions (eg. email + SMS), so total actions includes duplicates, sometimes quite a high number.
- The progress meter is showing total actions on a single page, not across the multilingual campaign. This means campaigners have to manually go in and edit the "starting value" to make the overall totals add up, and it's hard to keep them accurate and consistent

### This will be solved when
The number of actions displayed on the progress meter: 
- [ ] is equal to the number of action takers across the multilingual campaign if the page is part of one, plus the combined "starting values" set on any pages that are part of the campaign. This should be the same as this number in the AK dashboard if no starting values are set on any pages:

![Image](https://user-images.githubusercontent.com/22962348/172877058-c15f4b26-1f97-4e4a-a6f8-5e3d89d04bbd.png)

- [ ] if the page is not part of a multilingual campaign, the figure should just be the number of action takers on that page rather than number of actions, plus the starting value if any

**Comment by sukhada** [comment]
For issue #1:

It looks like you can specify optimizing for "unique user" rather than "total actions" in the Petition options of each page in a multilingual campaign:

![Screen Shot 2022-08-04 at 4 14 28 PM](https://user-images.githubusercontent.com/1696078/182970845-480860f5-d238-4025-b463-085ded8a830a.png)

I think that would allow us to get the number of unique action takers.

For issue #2:

I'm actually seeing that the numbers in an individual petition page seem to be for the total actions across the multilingual campaign.

For example, for this petition page: https://act.350.org/sign/Apr-22-listr-us-jugg-DropEACOP/, which has 6423 action takers (can be seen here: https://act.350.org/admin/core/multilingualcampaign/282/overview/), has a total of 21,925 actions taken so far. I also confirmed that the "Progress Meter - Starting Value" was 0.

Does that make sense, or am I missing something?

**Comment by rachelhbd** [comment]
Thanks @sukhada, you're right! Not sure how I missed that on #1 thank you, that does appear to update the totals in the live thermometers

For #2, we've been digging into this as well on our side and it does seem like this is resolved- even where we were previously seeing persistent count issues. I wonder if there was previously a bug on AK's side that they fixed, although I haven't seen it in the release notes lately. I'll run some more checks on this one, but it does seem ok for now!

**Comment by aaronelliotross** [comment]
Just a note that the counts won't combine if the multi-language campaign only has pages with the same language, you need at least 2 different languages for the counts to combine.

**Comment by aaronelliotross** [comment]
I don't know how often we use this feature, so maybe not worth it... 

But we could avoid the "shadow" page by writing a report to find the multi-lingual campaign pages and add the counts in JS on the front-end:

Either:

1. If we can use the petition template to get the multi-lingual campaign page ids into the HTML, we could loop over them in JS and render the ak-template

2. We could write a custom end-point (Do we have somewhere that we can proxy calls to the ActionKit API?) that takes the page id or name and returns the combined count by calling a custom report. The report would be a query that joined page, multi-lingual campaign and petitionactions.  The reports API has caching built-in, but we'd probably also want our end point to cache agressively.
