### ISSUE TITLE
Simplify one-time or monthly (3-way test with 2 ActBlue versions)

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#359]
### Context We'd like to test updating the design of the "Onetime vs monthly" donation buttons since we know that users sometimes get confused by this. The goal at this stage is to reduce confusion & increase page conversion, rather than to specifically optimise for monthly donations (that can come later).

First we'd like to test the minimal layout used by ActBlue:

**A. [Simple buttons with a checkbox on the selected item](https://secure.actblue.com/donate/jun-22-em-us-climate-disasters-redirect/?action_id&#61;25558553&amp;akid&#61;.2483206.ZpvPZ4&amp;ar&#61;1&amp;rd&#61;1&amp;refcode&#61;em20220617-us-1-mrtesting&amp;source&#61;em20220617-us-1-mrtesting)** - ignore the comments about other features below, we're just interested in the monthly toggle part for now!
![Image](https://user-images.githubusercontent.com/22962348/180977447-b8f52a2b-f6b7-420a-8780-1b0e76b0ae49.png)

The design doesn't need to be _exactly_ the same as ActBlue where it makes sense to follow existing 350 design conventions

**B. We'd also think it's worth testing [an alternate version used by AB with some upsell text](https://www.sunrisemovement.org/donate/):
![Image](https://user-images.githubusercontent.com/22962348/180977839-f7952703-b4d5-4d09-9537-5f8af4fb041d.png)**

It would be good to have the option to do an A/B or A/B/C test here depending on how much traffic we have. We could plan to make the minimal layout A. the standard approach in the testing template (assuming we will make that the default if it passes), and then add B as a custom page field.

For the purposes of testing, we can try the text ActBlue uses, so we'd also need to be able to edit the bubble text.

### Custom page fields:
Editing upsell text: I think we can re-use the existing custom page field for editing the text of the upsell box with the arrow pointing to the one-time/monthly toggle: 
![Image](https://user-images.githubusercontent.com/22962348/180978769-3bab61e1-8200-4fd8-9a29-eb3a7f95b618.png)

Show/hide upsell bubble: I've also created a new custom page field `donate_monthly_upsell_show_vs_hide` we can use to show/hide the upsell bubble for testing:
https://act.350.org/admin/core/allowedpagefield/donate_5Fmonthly_5Fupsell_5Fshow_5Fvs_5Fhide/change/

Show/hide one-time and monthly options: Our donate pages allow us to vary whether or not monthly donations are included and which is the default (see custom page field: https://act.350.org/admin/core/allowedpagefield/donation_5Fonce_5Frecurring_5For_5Fboth/change/) - we should preserve these options. For the purposes of testing we can use the "both"/default variant which shows both options and defaults to one-time

Any user-facing text should be enclosed in language strings so we can translate it. We already have `{% filter ak_text:"donate_make_it_monthly" %}` pre-translated, but can update the text if we change the default

Our current form changes the upsell bubble to "Thank you for choosing a monthly donation!....". For the moment we can hide this option and just keep the bubble the same whichever item is selected, as ActBlue does

### Acceptance criteria:
- [ ] Monthly upsell option A. is a simple button toggle with a checkbox to clearly show selected item
- [ ] Monthly upsell option B. uses custom page fields to add a small additional bubble for upsell text, with a clear arrow pointing, and which stays static whether a one-time or monthly donation is selected 
- [ ] Both of these options above are available for testing
- [ ] Keep current setup where upsell bubble text is editable via custom page field donate_monthly_upsell_bubble (per page) and {% filter ak_text:"donate_make_it_monthly" %} (language string, affects all pages)

### Rollout notes:
- Once this passes testing, we can update the lang string "donate_make_it_monthly" with the default monthly upsell test. This would need translating as well

**Comment by sukhada** [comment]
@rachelhbd I have this up here: https://act.350.org/donate/qa-apr-22-em-us-earth-month/, let me know if you'd like me to tweak anything from a design standpoint!

**Comment by rachelhbd** [comment]
Thank you! Asked Maria, Bianca and Cliff if they have anything
It looks great to me. I just wonder if the font size of the upsell bubble is a tiny bit too small to be accessible? I see that the Actblue version is also small/smaller than the rest of the text - but still to my eyes/screen looks a bit bigger. Maybe worth going up a notch?

**Comment by rachelhbd** [comment]
We got the thumbs up from Bianca on this! And I think it's not a must have, but if we can increase the font size so it's the same as the "Secure donation..." line underneath the button, I think we'll be good here - looks like that's:

![Image](https://user-images.githubusercontent.com/22962348/184372313-1092f39d-f197-4d97-b926-cdc90f023790.png)

**Comment by sukhada** [comment]
@rachelhbd this is updated! https://act.350.org/donate/qa-apr-22-em-us-earth-month/

**Comment by rachelhbd** [comment]
Font size looks good, thanks! Michael also [picked up an edge case bug](https://350team.slack.com/archives/C029R3U6G8Z/p1660385140310139?thread_ts=1660241403.078499&cid=C029R3U6G8Z) in Firefox, where if you select a monthly donation and then refresh the page, the tick moves back to the default one-time but the blue colour/selection stays on monthly

![Image](https://user-images.githubusercontent.com/22962348/185241795-2fbd77d3-04ec-4ee6-9368-f6879c10c84c.png)

they said "on both linux and mac it works fine on chrome but not on firefox" - and I was able to recreate in mac/firefox, but mac/chrome and mac/safari are fine

**Comment by rachelhbd** [comment]
Also, for planning the release timeline - is this one that should go into Develop or straight into v3 when we've done all the QA?

**Comment by rachelhbd** [comment]
Hey @sukhada I created a page with the minimal version as well and noticed that there isn't a check mark visible (chrome/mac), would it be possible to add this too? 
https://act.350.org/donate/qa-apr-22-em-us-earth-month_copy/
<img width="401" alt="Screenshot 2022-08-18 at 10 14 30" src="https://user-images.githubusercontent.com/22962348/185358379-81041a2a-56bd-43db-a2e9-2386d418fa15.png">

**Comment by sukhada** [comment]
@rachelhbd just to confirm, you want to have the checkmark on all donate forms? Otherwise I think that form doesn't have the "Donate Monthly Upsell" custom page field enabled

**Comment by rachelhbd** [comment]
Ah great! Yes, please we'd like the checkmark on both versions/all donate forms - it's in both the ActBlue variants we were looking at (A and B) and we're hoping it will increase user clarity on which option they've selected. The custom page field is more for testing adding the little bubble with the arrow pointing down.
I can see that might make things a bit more complex though code-wise, so if it needs more time that's ok!

**Comment by sukhada** [comment]
@rachelhbd This has been updated! Just as a heads up, I haven't added the donate monthly upsell bubble to the default recurring option pages (e.g. pages like this: https://act.350.org/donate/donate-just-recovery-uk-monthly/, that have a default value of "Donate Monthly"). Let me know if you'd like the upsell on these pages as well, and I can add that in

**Comment by rachelhbd** [comment]
@sukhada that makes sense for default recurring pages, thanks for thinking of that case!

**Comment by sukhada** [comment]
@rachelhbd Thanks to Julia for spotting this, will update! I was also wondering if we want to keep the current monthly upsell bubble if the new view is not enabled? 
<img width="362" alt="Screen Shot 2022-08-25 at 11 39 41 AM" src="https://user-images.githubusercontent.com/1696078/186643977-639fa9da-bb6b-4f21-8262-a86dff95afd7.png">

**Comment by rachelhbd** [comment]
Hey @sukhada, thanks for updating! We wouldn't want the current monthly upsell bubble for version A -- for this we're looking to replicate Screenshot/version A above, which is a minimal layout option used by ActBlue and doesn't have a bubble. 
<img width="240" alt="Screenshot 2022-08-29 at 09 39 11" src="https://user-images.githubusercontent.com/22962348/187160606-18278fd2-7e40-4935-95d3-d59911e2849a.png">

For A, I think your initial prototype without the "MAKE IT MONTHLY" heading, and with the simple "Donate once | Donate monthly") is perfect actually - we just want checkmarks as well to make it clear which option is selected.

Screenshot/version B above is intended to be equivalent to & an improvement on the current upsell bubble.
<img width="292" alt="Screenshot 2022-08-29 at 09 39 24" src="https://user-images.githubusercontent.com/22962348/187160624-a09bf71f-76b2-4ff4-bf84-04ab4165778f.png">
And it's fine that we don't have the heading in this version as well, because our upsell bubble text says that.

For implementation, we are planning to test these against the current version, and if it passes, version A and B will be the two standard options that are toggle-able via a custom page field. We'll see which passes testing best, but I imagine A will be a good choice on mobile at least as it's compact. 

(If this does happen, it would be good to keep a copy of the original code either in Github or by copying & archiving the template - whatever you think would be best there)

Does that sound right to you?

**Comment by sukhada** [comment]
Got it, that makes sense!

**Comment by rachelhbd** [comment]
hey @sukhada when do you think it's looking feasible to have the fix in here? We were hoping to launch the one-time/monthly test on Friday, and are figuring out timings to start a sign > donate > share test (which will also use the new toggle as it's in the Aug templateset)

**Comment by sukhada** [comment]
@rachelhbd oops, I'm so sorry, I forgot to push up this change! Should be updated now!

**Comment by rachelhbd** [comment]
No worries, thanks - all looks good now for the default setting (offer both one-time and monthly, default to one-time)! 🙌 
<img width="425" alt="Screenshot 2022-08-31 at 14 03 16" src="https://user-images.githubusercontent.com/22962348/187685162-c13321fe-d942-4414-843d-1da287d518fb.png">

**Comment by rachelhbd** [comment]
Headsup I did find an edge case -- if the custom page field is set to recurring as the default...
<img width="711" alt="Screenshot 2022-08-31 at 14 05 03" src="https://user-images.githubusercontent.com/22962348/187685907-91ff6711-d16d-440b-8c2d-5f1f1adcb408.png">

.... it looks like in Chrome on mac, the checkmark is not showing up on the correct option on first load:
<img width="352" alt="Screenshot 2022-08-31 at 14 05 19" src="https://user-images.githubusercontent.com/22962348/187685942-25e72758-232a-495a-83e0-105dfb954afc.png">

Is that a quick fix or should I add it to the Sept sprint? (We won't need to use this setting for the A/B test, so it's not urgent)

**Comment by rachelhbd** [comment]
Also, I was also thinking a bit about this question you raised above:
> I haven't added the donate monthly upsell bubble to the default recurring option pages (e.g. pages like this: https://act.350.org/donate/donate-just-recovery-uk-monthly/, that have a default value of "Donate Monthly"). Let me know if you'd like the upsell on these pages as well, and I can add that in

On second thoughts, I think we can apply the same formatting to the default recurring pages too, because we can use this custom page field to control the text in the upsell bubble for design B:
<img width="694" alt="Screenshot 2022-08-31 at 14 13 57" src="https://user-images.githubusercontent.com/22962348/187687421-ba6d86a3-f05d-439c-8193-42ee118dcbff.png">
And there might be cases (like for mobile) where we want to use the minimal design A and have the explanatory text in the form into. Is it best if include that tweak in the Sept sprint?

**Comment by sukhada** [comment]
@rachelhbd I just updated based on your feedback, let me know if it looks good!

**Comment by rachelhbd** [comment]
Woo hoo that covers everything, thank you! I tried all the One-time // Recurring and Show // Hide bubble combinations and everything looks good
