### ISSUE TITLE
Sign > share > donate flow: option to move donation ask to 2nd step

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#367]
## Context 
 The Sign > Share > Donate flow is a variant of the after-action flow used for signup pages and petitions.   The flow keeps the user on the page after taking action, and offers them a series of Y/N options asking them to share and then donate.  

Whether users see a standard thanks page or the flow is controlled by a custom action field on the page: after_action_next_step. The flow currently only works for pages hosted in ActionKit (embedded pages default to the standard thanks page)  

We are not getting a good donation conversion rate with the current flow, which means that the flow rarely gets used for global actions (we use a fundraising redirect instead), however this means we are not giving people the opportunity to share our actions. 

So this and follow-up tickets with this theme will be finding ways to optimise this flow for both donations and shares, and add flexibility for global and embedded actions.

### Goal
The goal of this ticket is to provide the option for the donation ask to be the second step, followed by a share ask. 

I've added a 3rd option called "scroll-donate" to the custom page field which can be used to toggle this in the admin interface for the page: https://act.350.org/admin/core/allowedpagefield/?o=name&ot=asc 
![Image](https://user-images.githubusercontent.com/22962348/182151144-60a7bfb2-7929-45bb-a3e2-cea3135e8f7b.png)

I've made some proposals below for how this could work. We don't have design mock-ups, hoping we can move existing components around to achieve this. If this is unclear for dev and we find we need a design, we can move this to the Sept. Also open to other ideas about the design/UX if you have suggestions here!

### This will be done when

**Step 2**
- [ ] when "scroll-donate" is selected for custom page field "after_action_next_step", the current Step 3 is moved to step 2, including the donate buttons:
![Image](https://user-images.githubusercontent.com/22962348/182159107-af669bc2-a885-45c2-b18a-28be4b02f99a.png)

- [ ] instead of the "Not ready to donate" link on Step 2, we would have an option taking the user to the share step 3. This could be simply a "No, not now" button using the same design as the current step 2, which would take people directly to step 3
![Image](https://user-images.githubusercontent.com/22962348/182159032-4290af22-67b3-4537-958c-3f71b7399460.png)
- [ ] If the user does click the donate buttons, they would be taken to a donate page as they are currently (we will need to find ways to optimise shares after donating, but will tackle that separately)

**Step 3 (plus additional thanks step)**
- [ ] when "scroll-donate" is selected, the current share step would be moved to Step 3:
![Image](https://user-images.githubusercontent.com/22962348/182161459-fe75ec1f-930b-4c54-a0dd-8186329625c7.png)

- [ ] If they click "No, not now", we need to end the user journey in a simple way. The same is true for if they click "Share on facebook" - currently the facebook share opens in a separate window but the flow will scroll down to a donate ask. Can the page scroll down to show the user a simple thanks message for both of these scenarios? I created a new custom page field to make the thanks page text editable, "afteraction_thanks_text", so that campaigners can add a thanks message.
- [ ] Ideally the thanks message would allow HTML, so campaigners can include a simple link or button

**Top progress bar**
- [ ] when "scroll-donate" is selected, the order of the items in the top progress bar would be switched to Donate then Share for both steps

### Example pages
The example page screenshotted above is https://act.350.org/sign/demo-share-page/ 
We also have this page which displays which custom page fields control which elements: https://act.350.org/sign/custom_page_field_demo_petition/

**Comment by sukhada** [comment]
@rachelhbd I have a version of this working here: https://act.350.org/sign/sukhada-demo-share-page. Whenever you can, it would be awesome if you could take a quick look just to make sure the flow seems right to you!

**Comment by rachelhbd** [comment]
Great thanks @sukhada taking a look!

**Comment by rachelhbd** [comment]
thanks @sukhada! it's looking good :) 

Please could we have a more prominent option for those who can't donate on step 2? Like a "Not ready to donate" white outline button, below the donate amount buttons?  I screenshotted above a "No, not now" button which is about the right style I think, but looking at it again "Not ready to donate" could be better text. 

I could also set up a custom page field to include in the code so we can make the "Not ready to donate" button text editable and testable?

I'm open to other UX options here, I just think that small hyperlinked text for users that can't donate won't be visible/self-explanatory enough and folks will drop off without getting to the sharing part

**Comment by sukhada** [comment]
@rachelhbd this should be updated now - we can also make the button smaller if you'd like: 
<img width="711" alt="Screen Shot 2022-08-15 at 9 04 28 PM" src="https://user-images.githubusercontent.com/1696078/184795534-a8571f5e-0bd9-4d86-9da2-39258efe3dec.png">

**Comment by rachelhbd** [comment]
I think that's great - there might be some layout updates to come in a future sprint, but we can start testing this design already

**Comment by rachelhbd** [comment]
hey @sukhada I've done some QA'ing and it looks good! Because this a relatively small tweak and is in a custom page field I think let's go ahead and get this into v3 (via Develop if that's easiest, up to you)- I'd like to get this to live and get some early user feedback whilst we plan the next round of work here

**Comment by rachelhbd** [comment]
Oops sorry, I spoke too soon - I'm seeing a floating "Add your name" button on iphone/Safari which I had assumed was a more general UX bug but I think I'm only seeing it when the donate-share custom page field is selected:

![Image](https://user-images.githubusercontent.com/22962348/185256133-cfa640ab-b20c-4685-9af0-dd2194ea163b.PNG)
![Image](https://user-images.githubusercontent.com/22962348/185256132-e2ece0f7-8f82-4123-854f-329934ae41fe.PNG)

Can you see the same?

**Comment by rachelhbd** [comment]
If you'll be looking at this some more, if it would be a low-lift would it be possible to open the donation buttons in a new tab (so people can find the share links if they want to)? This would be a temp solution probably until we work on a better flow here. It's not a must have - we can release v1 without and do this in the Sept sprint if that's easier

**Comment by sukhada** [comment]
@rachelhbd both of these things have been updated, let me know if you're still seeing any issues!

**Comment by rachelhbd** [comment]
fab - the iphone/safari button looks sorted :D

the opening separate tab works too! (I guess I was imaging that a click on either the donate buttons or the "not ready" button in that section would trigger the sign > share > donate page moving to step #3, but I didn't specify that -- and it probably involves scripts and things -- so we can table that for now until we know exactly what we want to do with this flow)
