### ISSUE TITLE
Donation buttons visible on donate step if alternative donation page custom field url is used

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#368]
See #367 for more context on the Sign > Donate > Share flow

Currently we have some missing functionality with the custom page field [afteraction_donate_alternate_url](https://act.350.org/admin/core/allowedpagefield/afteraction_5Fdonate_5Falternate_5Furl/change/?_changelist_filters=o%3Dname%26ot%3Dasc) where if an alternative donate page is added using this field, the user will just see a "Donate" button rather than amount buttons

Here's an example of a page with this custom page field in use: https://act.350.org/sign/demo-share-page-alt-donate/

On the donate step we just see a simple button:

![Image](https://user-images.githubusercontent.com/22962348/182167577-14e56a89-287e-443b-a3c0-2a17ee1f1672.png)

Is it possible to instead include the donate buttons as shown on https://act.350.org/sign/demo-share-page/, which is using the default donate page?
![Image](https://user-images.githubusercontent.com/22962348/182167946-45d27dab-c624-489f-8f7b-c01f939c0f6f.png)

If it's a heavy lift to show the adapted amounts/currencies, then we could postpone this one.

**Comment by sukhada** [comment]
@rachelhbd it looks like we also use `afteraction_donate_alternate_link_text` in this code block, and the button text is either set to this `afteraction_donate_alternate_link_text` or to `Donate` as a back up. Would a good solution for this be to check if `afteraction_donate_alternate_link_text` is set, and if so, use that as the button text, and otherwise just use the default button amounts with the URL going to the `afteraction_donate_alternate_url`?

**Comment by rachelhbd** [comment]
@sukhada thank you for digging here! 

I can't think of a scenario where we'd need the ability to replace the amount buttons with a text-based Donate button, so we could retire `afteraction_donate_alternate_link_text` entirely

Would it be feasible to check if `afteraction_donate_alternate_url` is set, and if it is to have that override the `{% include_tmpl templateset.custom_fields.afteraction_donate_url %}` tag?

![Image](https://user-images.githubusercontent.com/22962348/188600994-e51ed784-5ad9-4912-9d45-5973afb3998b.png)

**Comment by sukhada** [comment]
@rachelhbd yes, I think that would work!

**Comment by rachelhbd** [comment]
Great, let's go with that then!

**Comment by sukhada** [comment]
This is ready to QA using this templateset: https://act.350.org/admin/cms/templateset/460/templates

**Comment by rachelhbd** [comment]
This looks good thanks @sukhada!

I was testing this page: https://act.350.org/sign/sukhada-demo-share-page/ 

One thing I noticed was that if the url as entered in the custom field ended in a / mark, eg. `https://act.350.org/donate/qa-apr-22-em-us-earth-month/` as in the current demo page, then the resulting url has two // marks after it:
`https://act.350.org/donate/qa-apr-22-em-us-earth-month//?amount=3&source=aa_16064&currency=GBP`
It seems to be working fine, but do you think that's likely to cause problems? 

We could try putting a note in the guidance notes for the custom page field, if it's not an easy fix to standardise for whether or not the user includes the / mark

**Comment by rachelhbd** [comment]
Thanks @sukhada - I'm still seeing the two // marks but it might be my cache. No problem either way though if it won't cause issues!

**Comment by sukhada** [comment]
@rachelhbd woops I just realized I hadn't pushed my changes up - should be fixed now, sorry for the trouble!

**Comment by rachelhbd** [comment]
All good, yep that works, thanks :)

**Comment by rachelhbd** [comment]
I won't do browser/device QA here as there's no new front-end, but let me know if you think I should check this again after we have https://github.com/350org/ak_intl_v3/issues/382 finalised!
