### ISSUE TITLE
Add trackable "Copy link" button to share links on donation pages

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#369]
User story
-
As a campaigner, I'd like to be able to easily show supporters "copy link" share asks on redirected donate pages which track the relevant data, so that we can offer users share asks beyond twitter and facebook and track the list growth benefits

Context
-
When we have actions redirect directly to a fundraising page, and we're not using the Sign > Donate > Share flow, we miss out on the opportunity to ask people to share our action, and it doesn't sit will with some supporters who can't donate for that to be the only option offered to them.

Based on https://github.com/350org/action-tools/issues/43 we know what share links should look like in this scenario: `https://act.350.org/share/link?type=TYPE&action_id={{action.id}}&short=1` where TYPE is tw, fb or ot depending on the share channel 

"Passing the action ID allows the share to be linked to that action, and to any earlier shares, enabling multi-generation share tracking."

#### Previous/historical tests for ref 
 
> We previously planned to test a "can't donate" option on a number of donation pages, but the action didn't get launched due to a change of campaign plans.
> (Test plan: https://docs.google.com/document/d/1gHw2Tpq6wzedkkvioDi3KaT9BzT9UMMs_O-ob19ML4Y/edit)
> 
> There were are a few other issues with this test:
> - we weren't using AK's built-in share tracking, so we wouldn't have been able to track the number of users from shares
> - we had to have multiple tests running because of the number of variants, to make sure each variant was sharing the right link- this was time-consuming to set up and would have been in the data analysis as well
> - the UX was pretty basic and easy to miss:
> 
> Page: https://act.350.org/donate/feb-22-em-uk-fossil-fuels-did-this-redirect/?variation=406
> One of the tests: https://act.350.org/admin/lab/test/189/change/
> 
> ![Image](https://user-images.githubusercontent.com/22962348/182172729-a38ab7c9-cb21-4f2a-b4e3-d49afae10468.png)

This sprint
-
I have a prototype here of this in action, adding the share buttons into the intro text: https://act.350.org/donate/feb-22-em-uk-fossil-fuels-did-this-redirect_RHtest2/

This can be previewed by adding action id and akid onto the link: https://act.350.org/donate/feb-22-em-uk-fossil-fuels-did-this-redirect_RHtest2/?action_id=26066339&akid=.2483206.ZpvPZ4 

(a) **Share link button** - could we add functionality that when the user clicks on the third share button (type "ot"), the link is copied? With [this example page](https://act.350.org/donate/feb-22-em-uk-fossil-fuels-did-this-redirect_RHtest2/?action_id=26066339&akid=.2483206.ZpvPZ4), the user should copy the short url eg. https://act.350.org/s/2232898.EBBgGo  
(b) **Icon** - could we add an icon appropriate to "copy link" for the 3rd share button, eg. something like a simple chainlink or https://www.shutterstock.com/image-vector/copy-link-icon-thin-light-regular-2102214037

Future sprints
-
(d) Design - Out of scope for now but for a future sprint - once we know the winner of the design tests, we could see if we could make this whole "Can't donate? please share" asklook any better in terms of formatting and positioning, on both desktop and mobile
(c) Custom page field - once we have a version that we've tested we can put the code in a custom page field so it's easy to add to any donation page & test. I've created one here: https://act.350.org/admin/core/allowedpagefield/donate_5Fshow_5Fcant_5Fdonate_5Fshare_5Fask/change/

**Comment by sukhada** [comment]
@rachelhbd how do you want to specify the petition URL that is copied? e.g. in your example, how do we know to copy the short url: https://act.350.org/s/2232898.EBBgGo?

**Comment by rachelhbd** [comment]
Hey @sukhada, the link is autogenerated by ActionKit from the original url https://act.350.org/share/link?type=ot&action_id={{action.id}}&short=1, but I think it's a multi-step process (first they add in the actionid to the url from the url parameters, and then because the url contains '&short=1' AK transforms it to a short url). 

I just sent a help request to AK with the subject "How to create user-copied share links" and cc'd you, hoping they can point us in the right direction!

**Comment by rachelhbd** [comment]
Alright here's what we have from Shannon:
> You're correct that making a call to /share/link will generate a sharable link when passed an action ID, and I see that you've also figured out the type=ot and short=1 parameters, which is great.
> 
> Rather than linking directly to /share/link, I'd recommend making an ajax call to /share/link to generate the link itself, then populating a text box, button, or some other HTML element with the results as per your preference of how you want the users to interact with that.
> 
> Let me know if you have any questions about this or get stuck!

**Comment by sukhada** [comment]
@rachelhbd if you preview https://act.350.org/donate/feb-22-em-uk-fossil-fuels-did-this-redirect_RHtest2/?action_id=26066339&akid=.2483206.ZpvPZ4 with the new Oct templateset, this should be ready for QA!

**Comment by rachelhbd** [comment]
Ok great! Here's the link including the preview: https://act.350.org/donate/feb-22-em-uk-fossil-fuels-did-this-redirect_RHtest2/?action_id=26066339&akid=.2483206.ZpvPZ4&template_set=350.org%20-%20International%20(With%20the%20Ranks%20-%20October%202022)

The facebook button is carrying forward the shortlink: https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fact.350.org%2Fs%2F2250120.AoJP5e

And so is the twitter button: https://twitter.com/intent/tweet?url=https%3A%2F%2Fact.350.org%2Fs%2F2250125.pb9Ggr&text=Join+the+Climate+Movement

And the link share: https://act.350.org/s/2250123.holGPm

I think in a future iteration we could figure out how to make it clearer for the user that when they click on the link step, the url is copied to clipboard, I'll ask Cliff to have a think about that add it to Future steps (d) above

But for now I'll mark this as done and we can collect some feedback from folks for the next iteration

**Comment by rachelhbd** [comment]
Hmm actually - perhaps I was being a bit quick there, thinking that all the code was in the admin interface, in the Ask text here: https://act.350.org/admin/cms/donationform/1335/change/?page=16377, rather than the templateset at the moment. But @sukhada did you make some changes to the October templateset too?

**Comment by sukhada** [comment]
No, the changes should all be in the admin interface!

**Comment by rachelhbd** [comment]
Ah brilliant - then I'll close and we can get some feedback for the next iteration
