### ISSUE TITLE
Improve donation page HTML autocomplete functionality

### ISSUE THREAD

**Issue by cjmabry** [350org/ak_intl_v3#370]
**Summary**
Users have observed that auto-filling on AK donation fields is inconsistent, and browsers as well as extensions don't properly recognize the correct fields and may pre-fill the wrong type of information. This can be rectified by setting appropriate values for the autocomplete value, as explained here: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values

Edit `donate.html` in the template set and add appropriate autocomplete values to the form, including setting autocomplete to "on" on the parent form, and specifying specific values to each input, such as `family-name` for last name/surname or `email` for email address.

**Testing**
- Major browsers should auto-fill all appropriate form fields with correct information
- Major password managers should auto-fill all appropriate form fields with correct information

**Supporting resources:**
- https://web.dev/learn/forms/autofill/
- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by cjmabry** [comment]
@rachelhbd converting this to an issue so I can flesh it out a bit more!

**Comment by cjmabry** [comment]
@rachelhbd sorry to double-ping, but this issue is scoped from the autofilling side - I have not expanded on any Google API/Apple Pay things as I think we should break that one down further and discuss where and why it might be needed.

**Comment by sukhada** [comment]
@cjmabry There is also this Prefill feature on ActionKit that we could look into implementing: https://act.350.org/docs/manual/guide/prefill.html#cross-site-prefill. All we have to do is add `{% load_prefill %}` to the `wrapper.html`, so I think we could just try it and see how well it works

**Comment by cjmabry** [comment]
@sukhada that's a good idea, maybe we should break that into a separate issue and scope out.

**Comment by rachelhbd** [comment]
@cjmabry no worries, that makes sense to break things out like this yep! I initially had them together as that's the way they came up in conversation and I wasn't sure if it was related - but now realising there were two types of "prefilling" being discussed there

So adding the correct autocomplete tags sounds like a fiddly but not particularly challenging task?

And then also ++ to breaking out the AK EveryAction user data prefills separately to do a bit of scoping on that too

**Comment by rachelhbd** [comment]
@cjmabry I think let's prioritise this one for the September sprint, ie. setting appropriate values for the autocomplete value. It seems concrete, doable, and definitely meets our goals of "de-annoying"/removing blockers to donations

Would you be up for turning this into a ticket that's ready for dev work, or starting a new one? Or do you think it's ready to go already?

**Comment by cjmabry** [comment]
@rachelhbd yup, I can get this ready to work on!

**Comment by rachelhbd** [comment]
Thank you! Please can you change the status to "Ready for dev" when you're done?

**Comment by cjmabry** [comment]
@rachelhbd this one is ready to go, I just updated original comment but can break out separately if it makes sense to clean up.

**Comment by rachelhbd** [comment]
That's fine I think we can keep things here - thanks :)

**Comment by sukhada** [comment]
@cjmabry this should be ready to QA using this templateset: https://act.350.org/admin/cms/templateset/460/templates, let me know if it's working as expected!

**Comment by rachelhbd** [comment]
thanks! here's a demo page using this templateset https://act.350.org/donate/demo_donation_uk_rhsept22

I've tried it with Dashlane which worked as expected, but figured we might need a few people to try this with different browsers and pw managers so have put a call out for help here and created a tracking sheet: https://docs.google.com/spreadsheets/d/1__wxt78U6xWQVFaOQYAhqwdPJg7Pt3a_wVPCzcDc1U8/edit#gid=0

**Comment by rachelhbd** [comment]
This has passed QA here!
https://docs.google.com/spreadsheets/d/1__wxt78U6xWQVFaOQYAhqwdPJg7Pt3a_wVPCzcDc1U8/edit#gid=0

**Comment by michaelsnook** [comment]
This appears to be complete so I'm closing. (re-open if I'm wrong!)

**Comment by cjmabry** [comment]
This has not been deployed yet but I'll consider done and then handle production deploy in a separate release ticket.
