### ISSUE TITLE
Move Name and email fields to step 2 of donate form

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#378]
Based on our initial scoping in https://github.com/350org/action-tools/issues/40, we'd like to propose re-ordering some of the fields on our donate forms and adjusting the field layout:

- First Name and Last Name fields are moved from Step 3 to the top of Step 2
- Email field is moved from Step 3 to below the Last Name on Step 2

To reduce vertical height of Step 2:
- First and Last name fields appear on same line, 50% width _(added based on conversation in comments below)_
- State/region and zip/postal code also appear on same line, 50% width _(added based on conversation in comments below, but only if it's a low lift given these fields are responsive based on country)_

This more closely mimics conventions used by similar orgs and mean that we are asking for email opt-ins on the same step as the email address field, so the goal is to provide a more logical experience for donors (which may increase conversion rates)

Notes:
- This does mean step 2 "Info" will be quite vertically long 
- For Paypal donations this will mean there are no fields to complete on step 3, just a "Continue to Paypal" button - that's okay for now, but we should revisit the Paypal flow separately

We would want to A/B test this change to see if it affects conversions

**Comment by cjmabry** [comment]
@rachelhbd I think this makes sense from a UX perspective, although the concern you raise about being vertically long is valid, especially on mobile. I would propose using two columns whenever possible, such as:
- first and last name on same line, 50% width
- perhaps doing the same to state/region and zip/postal code

Will defer to @alandmih on if this affects any ecommerce tracking.

**Comment by rachelhbd** [comment]
I updated the description at the top if the ticket to include those suggestions

**Comment by rachelhbd** [comment]
@alandmih have you got any concerns on this re ecommerce? maybe it's enough to make sure you review the PR? if not let's mark as "ready for dev"

**Comment by alandmih** [comment]
@rachelhbd No concerns from my end. I would only want to make sure to review the PR for changes around the "Continue to Paypal" button just to be certain that the tracking event is still fired upon user click of that button. Ok to mark as "ready for dev"

> @alandmih have you got any concerns on this re ecommerce? maybe it's enough to make sure you review the PR? if not let's mark as "ready for dev"

**Comment by sukhada** [comment]
This is ready to test on the Sept '22 templateset: https://act.350.org/admin/cms/templateset/460/templates. 

Also, just curious but would it make sense to move the billing address fields to step 3 since they are presumably only required for the credit card checkout option?

**Comment by rachelhbd** [comment]
Thanks @sukhada! Testing this out here: https://act.350.org/donate/demo_donation_uk_rhsept22/

It looks great except the Region / State / Province field is missing a line at the top of the field, when a European country is selected:

![Image](https://user-images.githubusercontent.com/22962348/192339334-c09a2f37-6c80-4912-8f23-032d2621f34a.png)

**Comment by rachelhbd** [comment]
Looks good, thanks!

**Comment by rachelhbd** [comment]
There were [a few things picked up in browser/device QA](https://docs.google.com/spreadsheets/d/1Yo1Ry_GIS18Nhvkh0ULA2w-jiOvBdP4H8KIOQj8OJSE/edit#gid=1764366087) here, but I think they are non-blocking, so this is ready to test

**Comment by cjmabry** [comment]
@mariaroper @sukhada did we want to plan to implement this after the results of the latest test?

**Comment by mariaroper** [comment]
Yes!
