### ISSUE TITLE
Update regional pixels

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#381]
We have a custom page field that allows users to be able to easily add a Facebook Pixel to ActionKit pages:
https://act.350.org/admin/core/allowedpagefield/page_5Fadd_5Fregional_5Ffb_5Fpixel/change/?_changelist_filters=q%3Dpixel%26o%3Dname%26ot%3Dasc 

We'd like to make a few changes to the setup:
- Add "350 Australia", pixel id 262385177432327 
- Add "350 France", pixel id 1093870721001969
- Update "350 Germany" to pixel id 440122750549924

I think these are updated in wrapper.html

For 350 ref, the updated codes are [recorded here](https://docs.google.com/document/d/1Bo9-LHsgIEWtvq1RNT8JHV5xSVUM3D5V4eonQ6vTf4c/edit#bookmark=id.hwu7p8wjtxqk)
and here is the [slack thread](https://350team.slack.com/archives/C0D6W7614/p1661440719348779?thread_ts=1661239685.907419&cid=C0D6W7614) with Laetitia

NB. When we're ready to merge to live, I'll need to update the custom page field with the new labels

I'm also not sure how we should QA this apart from checking the right pixel number is present in code view, so will check with Laetitia on that!

**Comment by sukhada** [comment]
This is ready for QA via this templateset: https://act.350.org/admin/cms/templateset/460/templates

**Comment by rachelhbd** [comment]
Thanks @sukhada, this looks good in the templateset - although do we also need to update the <noscript> fallbacks starting from line 268?

![Image](https://user-images.githubusercontent.com/22962348/192349260-b6ffade2-4a24-40fd-8312-2a35af26f04a.png)

I also created a demo page with the Sept templateset: https://act.350.org/sign/rachel-demo-share-page_sept22/  and set the FB pixel setting to 350 Germany via the custom page field -- I'm still seeing the old pixel code for Germany here (starting 974 in the image below), but is that because the JS file would be updated later in the process?

![Image](https://user-images.githubusercontent.com/22962348/192349975-1bd99607-33a3-428f-ae20-490bea191f72.png)

Also noting that before release I'll need to add 350 Australia and France into the custom page field dropdown list, but I won't do that til we're live to avoid confusion!

**Comment by sukhada** [comment]
@rachelhbd updated!

**Comment by rachelhbd** [comment]
Ok fab - looks good in the templateset, and am seeing the right code for Germany too in view-source:https://act.350.org/sign/rachel-demo-share-page_sept22/

**Comment by rachelhbd** [comment]
Also good to include in the next release :)
