### ISSUE TITLE
Add new background option for donate pages which increases accessibility

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#384]
User story
-
- As a user I'd like to be able to read donation page text easily
- As a digital fundraiser I'd like to remove any barriers to donation page conversations

Context
-
@cjmabry has mocked up some versions of the donate page template which increases visual accessibility, and we have picked a version to A/B test initially:

- Desktop: https://www.figma.com/proto/9o0tUU1krckXCBLzxjozB0/350-Donation-Accessibility-Ideation?node-id=502%3A139&viewport=3311%2C-1900%2C0.28&scaling=scale-down&page-id=0%3A1%3Ffuid%3D923664738342119661
- Mobile: https://www.figma.com/proto/pQhmob8CPilNzBz8AZtRiQ/350-Accessible-Donation-Design?node-id=602%3A17&viewport=583%2C293%2C0.97&scaling=scale-down&page-id=602%3A15%3Ffuid%3D923664738342119661

We're not sure if having a transparent background around the edges will work for every type of image. We've discussed different ways to treat the background image and would like to explore if we can control that using the existing [page background colour custom page field](https://act.350.org/admin/core/allowedpagefield/page_5Fbackground_5Fcolor/change/?_changelist_filters=q%3Dbackground%26o%3Dname%26ot%3Dasc)

### This will be done when
- [x] **Iteration A** - We have a version of the Figma mockups above built out and ready to test against our current templateset. This would be with the background image fully visible on desktop and mobile, no fade, and would be enough for this sprint so we could go ahead and start testing

### For a future sprint? - or could be included in this one if low lift
- [x] **Iteration B** -  Ability to test a plain blue background on mobile, whilst on desktop we are showing the same version with an image as as Iteration A. One way to do this could be to add another variant to the [page background colour custom page field](https://act.350.org/admin/core/allowedpagefield/page_5Fbackground_5Fcolor/change/?_changelist_filters=q%3Dbackground%26o%3Dname%26ot%3Dasc) list of options ^ which is "Transparent on desktop, plain blue on mobile"
- [ ] **Iteration C** - Ability to apply one of the standard fades in the background colour custom page field over both images

**Comment by rachelhbd** [comment]
Chris can do a mobile design and then will check out the template to see if it's implementable

Would need to run slightly darker blue colour past Cliff as well

**Comment by cjmabry** [comment]
@rachelhbd one flag is that the image on this page is fairly low resolution and compressed. This is obscured when the gradient is overlaid but a lot more noticeable when there is nothing obscuring the photo. Would we be able to get a higher resolution or uncompressed version of this image (https://dbqvwi2zcv14h.cloudfront.net/images/shadia-fayne-wood-sm.jpg) so that we can optimize it for this new design?

**Comment by cjmabry** [comment]
@rachelhbd here is a mobile variant. Because we're trying to keep contrast, we're not able to display much of the image on mobile. If this isn't suitable, we could play with a full color gradient overlay like what is currently on site but with a darkened gradient.

https://www.figma.com/proto/pQhmob8CPilNzBz8AZtRiQ/350-Accessible-Donation-Design?node-id=602%3A17&viewport=583%2C293%2C0.97&scaling=scale-down&page-id=602%3A15%3Ffuid%3D923664738342119661

**Comment by rachelhbd** [comment]
@cjmabry I'll meet with Cliff tomorrow to get some feedback on the colours & designs. 

How's it going with assessing the feasibility in the template of having one background section across both columns in the desktop version?

Is there anything else you think we'd need to prep to include this for dev in the October sprint? Thank you!

**Comment by cjmabry** [comment]
@rachelhbd we're good to go from my end. Would you like me to update this ticket with final requirements or make a new ticket, or would you want to handle that?

**Comment by rachelhbd** [comment]
Be amazing if you could, Chris (don't mind if you update or break out)!

**Comment by rachelhbd** [comment]
@cjmabry, got some feedback from Cliff:
- The colour choices are fine, and here's a colour palette Cliff's been working on for reference https://www.figma.com/file/Ramrq12bYk98jIbZh4hOBt/350-%7C-Web?node-id=717%3A1751
(we added the blue you used to the primary shades section as well as a slightly darker one if needed as well)
There's also a slightly richer blue in the "info and status" section which could be used for footers

- Cliff thought the faces are very visible in the image and might taking away from the form/affect the conversion rate, so it could also be good to test a version with a filter or fade over the image or blurring it slightly

- For mobile, he thought it might be better to skip the image for load time since you can't really see it. Or, we could apply the blue fade over it so that we can get away with a small image size and it won't be distracting

Curious what you and @mariaroper think about these options!

**Comment by mariaroper** [comment]
Here are my thoughts:
- overall i think both the desktop and mobile versions look great!!
- regarding Cliff's note about the faces being very visible: i don't know if i think that's a problem (for example, we have very visible faces on our ActBlue pages too), but definitely think it's a great idea to test a version where the image is a bit more faded!
- regarding the mobile design: i feel like for certain images (for example of a wildfire or a hurricane or something like that) it makes sense to be able to see a little bit of the image to get the right theme across, but i do agree with Cliff that when you can only see part of a face and part of an arm, there's not much of a point to it and we could skip it (or apply a fade). not exactly sure how to handle that but maybe we could make it possible to enable/disable the background image for mobile?

**Comment by rachelhbd** [comment]
hey @cjmabry moving this one to October - let me know if you think you'll have time to update the ticket ready for dev? Or I can have a go, but will be on monday. Thank you!

**Comment by rachelhbd** [comment]
I've updated the ticket and marked it ready for dev - please add anything I've missed @cjmabry, thank you!

**Comment by cjmabry** [comment]
Hey @rachelhbd this looks good, thanks for updating!

**Comment by sukhada** [comment]
I have an example page up here: https://act.350.org/donate/wtr_cleanup_web_donate_button. I added two options to the "Page - Background Color", one called 'New Accessible Option with Transparent Background' and another called 'New Accessible Option, Transparent on Desktop and Plain Blue on Mobile'

**Comment by cjmabry** [comment]
@sukhada fyi, it's hard to see in the designs but there should be a 2px border radius on the blue background to follow conventions of the home page.

**Comment by sukhada** [comment]
@cjmabry got it - updated!

**Comment by mariaroper** [comment]
Looks good to me, I will show it to Bianca as well and see what she thinks!

Just flagging that you can't see the text in the white admin menu at the top because the font color is also white

**Comment by cjmabry** [comment]
@sukhada sorry for late feedback but could we compress the background image? It's currently pulling in at 3mb. Let me know if you'd like me to do and can send you optimized asset.

**Comment by sukhada** [comment]
@rachelhbd updated here: https://act.350.org/donate/wtr_cleanup_web_donate_button, let me know if you'd like me to tweak anything else!

**Comment by sukhada** [comment]
@rachelhbd updated!

**Comment by rachelhbd** [comment]
Great that works! I think that's everything then

**Comment by cjmabry** [comment]
@rachelhbd I wanted to verify this is what you or @tryntastic were seeing on landscape mode:

![image](https://user-images.githubusercontent.com/3048335/203107658-9a3394ea-d3bc-4064-bb1b-4f24d55aac4d.png)

If so, I think that is acceptable since we are doing width-based media queries. We actually would prefer to get the crowd image in there if we have the space, so I would consider this good to go.

If you're seeing something else though please let me know.

**Comment by rachelhbd** [comment]
Ah gotcha thanks - @tryntastic please could you confirm?

**Comment by rachelhbd** [comment]
Noting that this is resolved and now in testing
