### ISSUE TITLE
Document process for updating affiliate / child templatesets

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#385]
We need to consider affiliate templates whenever we're QA'ing, or when making template changes that add new template pages

- At the QA stage, new files need to be recreated to the "[Nested templateset for QA](https://act.350.org/admin/cms/templateset/445/templates)" in the AK admin using extends tags, extending from Develop
- Major updates need to be QA'd using this templateset to check for conflicts 
- At the merge/go live stage, new files need to be recreated in the AK admin for each child templateset, using extends tags, extending from v3

**Comment by rachelhbd** [comment]
@sukhada tagging you in on this one

**Comment by sukhada** [comment]
Added documentation here: https://docs.google.com/document/d/1iZhzbGfsYa_dl9YJVMGQQNAusBgkbLDT_Fp_wuTfD4c/edit, once all the feedback is in, I can add it to the README!

**Comment by rachelhbd** [comment]
thanks much @sukhada, this looks spot on! I just added a clarification on when these updates happen in the process

@stbensonimoh fyi

**Comment by rachelhbd** [comment]
@sukhada please go ahead and add to the README when you're ready and then we can close 😄

**Comment by sukhada** [comment]
@rachelhbd I've added it to the Sept work branch - although I can also open a separate PR just for this, if you'd prefer?

**Comment by rachelhbd** [comment]
That works for me, @stbensonimoh let us know if you want to do anything different here!
