### ISSUE TITLE
Tentative: Dashboard to understand unsubscribe survey data

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#389]
We've gone live with the new unsubscribe pages and are starting to collect data: https://act.350.org/report/rh_new_unsubscribe_page_survey_responses_beta/ 

Could we put it on stack to prepare a dashboard that's easy to use for global & regional campaigners, including regional and language filters?

We'd also like to track the number of people resubscribing to Fossil Free news from the thanks page, and perhaps at some point track the % of people that unsubscribe in EN, FR, ES and then resub here: https://act.350.org/report/rh_users_resubscribing_ff_news_after_unsubscribing/

We also discussed these ideas for future (https://github.com/350org/ak_intl_v3/issues/348) but decided to focus on goal 1 for now

### For scoping
- [ ] Define data owner - ask digi C&O team for feedback on this

**Comment by rachelhbd** [comment]
@juliao762 I think you already started working on this but not sure if you have another ticket you'd rather use, and if you think it's something you can include in December?

**Comment by juliao762** [comment]
@rachelhbd - I have a ticket, will try to move it to PT sprints and will close this one!

**Comment by rachelhbd** [comment]
Okay great! Linking it here for reference https://github.com/350org/engineering-sprints/issues/95
