### ISSUE TITLE
Make bigger radio buttons, checkboxes and opt-in texts default

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#395]
### Context
We previously worked on updating the size and visibility of our all our radio and checkbox buttons as well as increasing the text size for the opt-in text, and currently have this implemented via a [custom page field](https://act.350.org/admin/core/allowedpagefield/form_5Fbigger_5Fradio_5Fbuttons/change/?_changelist_filters=q%3Dradio%2Bbuttons%26o%3Dname%26ot%3Dasc) which is set to default for new pages

I'd like to now retire this custom page field make this the default styling across all radio and checkbox buttons on all form types, including donation pages where we didn't originally apply this

Historic Gitlab tickets as we rolled this out incrementally:
[March 2021: Ability to test radio button size](https://gitlab.com/350/product-fa-sprints/-/issues/41)
[May 2021: Form fields alignment + sizing](https://gitlab.com/350/product-fa-sprints/-/issues/41)
[July 2021: Survey question input size](https://gitlab.com/350/product-fa-sprints/-/issues/54)
[Sept 2021: SMS opt-in bigger checkboxes](https://gitlab.com/350/product-fa-sprints/-/issues/76)

If it's helpful, I could also track down the related PRs in Github, but hopefully the code is searchable via the page field?

Also see #394 which builds on this one

### This will be done when:
- [x] All recently edited pages* including those that have "No" selected for the form_bigger_radio_buttons custom page field
eg. https://act.350.org/letter/Rachel-test-ES/?akid=.2483206.ZpvPZ4 
and https://act.350.org/sign/standard-petition-blue-background_copy/
still have the larger text size, radio and check boxes as in https://act.350.org/sign/standard-petition-blue-background
(*Noting that old pages will need to have an edit made before the changes are refreshed)
- [x] Donate pages also have the updating styling on Step 2 when a European country is selected
- [x] The changes are also reflected for pages embedded in wordpress
- [ ] If possible, once this is live we'd be able to hide the form_bigger_radio_buttons custom page field completely without affecting existing or new pages

**Comment by rachelhbd** [comment]
Hey @sukhada I changed this page https://act.350.org/letter/Rachel-test-ES/ to the October templateset but am still seeing the mini radio buttons, and the same on this donate page using the October templateset https://act.350.org/donate/feb-22-em-uk-fossil-fuels-did-this-redirect_RHtest2/

Is this because we need to update the relevant css files as well?

**Comment by sukhada** [comment]
hey @rachelhbd! I'm seeing the big radio buttons on the rachel test page: 
<img width="423" alt="Screen Shot 2022-10-21 at 3 29 45 PM" src="https://user-images.githubusercontent.com/1696078/197297749-b2eba0b4-847a-40f2-8cfa-1d33408ed4c5.png">

Also, I don't think that the radio buttons on that page are controlled by the custom page field, as the `feb-22-em-uk-fossil-fuels-did-this-redirect_RHtest2` has the page field set to "Yes, use bigger radio buttons and checkboxes", but the radio buttons are still small. Would you like us to look into increasing the size of these buttons as well?

**Comment by sukhada** [comment]
@rachelhbd I just looked into this and I think it would be best to add that in the November sprint, since it's not a super simple update.

**Comment by rachelhbd** [comment]
Sure! I'll bump this whole ticket to November if that works? If there's work you've already done here (eg looks like the first acceptance criteria was met) that makes sense to include in the October release we can do that, or we can just build on it in Nov

**Comment by sukhada** [comment]
If it's ok, we can include the first part in the Oct release, and the rest in November?

**Comment by rachelhbd** [comment]
Yes, that works! thank you

**Comment by rachelhbd** [comment]
@sukhada @cjmabry let me know if the next steps on this one for Nov are clear or if you want to chat to clarify anything!

**Comment by cjmabry** [comment]
@sukhada would you like me to break the remainder of this into a separate ticket or do you want to handle all on this one?

**Comment by cjmabry** [comment]
@rachelhbd this should now be fixed.

**Comment by rachelhbd** [comment]
Hey both, does it make sense bump this to the Jan or Feb sprints to wrap this up? (Or if you prefer, feel free to close and break out) I guess it would introduce some risks to be making unnecessary changes to the donate forms in December at this point, so maybe we don't try to release something like this in late Dec 

I wouldn't be 100% sure, but I expect this will involve moving code out of the individual action page templates and into wrapper.html

**Comment by cjmabry** [comment]
@rachelhbd I think I agree with that, I would avoid touching donate pages during this time if we can help it.

**Comment by cjmabry** [comment]
@rachelhbd @sukhada moved to January and set to scoping status to follow up on the remaining bits here.

**Comment by cjmabry** [comment]
@sukhada can take a look at this one as well.

**Comment by sukhada** [comment]
@cjmabry the fix for this should be ready in [this templateset](https://act.350.org/admin/cms/templateset/482/templates)!

**Comment by cjmabry** [comment]
@sukhada is this something Tryn could QA? If so can tag her in here.

**Comment by sukhada** [comment]
@tryntastic would you have capacity to QA this ticket? Let me know if you have any questions!

**Comment by rachelhbd** [comment]
hey @sukhada for QA, have you got some pages that use your dev templateset we could use to try out these? Looks like the acceptance criteria were

- [ ] Donate pages have the updating styling (bigger radio buttons & opt-in text) on Step 2 when a European country is selected
- [ ] The styling was also reflected for pages embedded in wordpress

**Comment by rachelhbd** [comment]
Oh yep, with @sukhada's tip to replace the css file in the browser with the staging css file `https://dbqvwi2zcv14h.cloudfront.net/ak-dev/ak-v3.css` I can see that the bigger radio buttons are showing up on donate pages. Just seeing if we can do the same with embedded pages...

**Comment by sukhada** [comment]
@rachelhbd that sounds good! I think embeds are a bit trickier to test with the staging CSS file update, so I think it makes sense to take a look after merging
