### ISSUE TITLE
No square box around selected items in wordpress embeds

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#396]
### Context
When forms are embedded in Wordpress with a white background, we're seeing a shaded box appear around checkbox and radio buttons, including GDPR opt-ins: https://350.org/rachel-test-petition-embed/
Could we remove this?

![Image](https://user-images.githubusercontent.com/22962348/193343477-57c38819-7bc0-4189-91c5-dd5429a75a19.png)

### This will be done when
- [ ] No shaded box appears around checkbox, radio or opt-in items on https://350.org/rachel-test-petition-embed/ and other embedded pages

**Comment by cjmabry** [comment]
@sukhada is this also related to the plugin linked here? https://github.com/350org/ak_intl_v3/issues/397#issuecomment-1275390270

**Comment by sukhada** [comment]
I think this is just coming from a Baseline style: https://350.org/wp-content/themes/baseline/sass/02-components/_forms-inputs.scss.

@rachelhbd this update as well as https://github.com/350org/ak_intl_v3/issues/397 are both changes that will have to be made to the website, not ActionKit.

**Comment by rachelhbd** [comment]
Yeah that's true, I was hoping you would also be able to propose edits to the wordpress Baseline theme for these ones. @rezziemaven's aware of it too. Do you have the right permissions or should we schedule a checkin with Rezzie about it?

**Comment by rachelhbd** [comment]
Oh I'm also seeing that #397 is related to a wordpress plugin too and is blocked there. This one seems a bit simpler, but looking at the Baseline file, I see what you mean it does seem like it was intentionally added.

Is it the "box-shadow" styling here?
> input[type="radio"]:checked:focus{
>   box-shadow:
>     0 0 0 0.12rem rgba(21,36,43,.25) // external outline to indicate :focus
>     0 0 0 calc(0.1em + 0.25rem) #fff inset; // inset shadow to indicate :checked
>   }

I would have thought that the box-shadow should only be around the actual checkmark box itself, maybe it's a mistake that it's around the text too. @itsboit do you have any context on this one by any chance?

**Comment by rezziemaven** [comment]
Hey @sukhada! If you have access to https://gitlab.com/350/web-tools/baseline then you can make the updates there in a fix branch and submit the merge requests to master. In our pipeline that deploys a push to master to all the production sites, I just added an action that compiles the `style.scss` file to `style.css`. In case it doesn't work as expected, then you might need to manually compile the `style.scss` to `style.css` locally in the command line and re-send as a new pull request.

**Comment by sukhada** [comment]
@rezziemaven opened a merge request here: https://gitlab.com/350/web-tools/baseline/-/merge_requests/57!

**Comment by rachelhbd** [comment]
hey @sukhada I see Rezzie merged it in and this looks good on the example page - are there any updates that need to be merged in ActionKit as well? If so let's include in the October release!
