### ISSUE TITLE
Clear opt-in and custom field validation formatting for embedded forms

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#397]
### Context
If you submit one of our ActionKit forms without any fields completed, eg. https://act.350.org/sign/rachel-test-petition/, then the required fields left blank are clearly highlighted with orange dots and highlighting - on or underneath each required field

![Image](https://user-images.githubusercontent.com/22962348/193347294-916a7411-01ac-4346-8fcf-ea088d606c99.png)

However when embedded in Wordpress (eg. https://350.org/rachel-test-petition-embed/), the user sees a callout in the browser, and then only the name and email validation messages appear in the correct place, and with orange highlighting:

![Image](https://user-images.githubusercontent.com/22962348/193349107-dabe8579-a666-4f4c-b013-23e9109f8dc1.png)

The custom fields does have a validation message directly underneath but it's not formatted with an orange dot and highlighting, so is hard to see:
![Image](https://user-images.githubusercontent.com/22962348/193349155-2c2c30e6-8010-40fb-a44a-1a5c4183600b.png)

The GDPR opt-in is shown underneath the submit form and privacy notice, along with repeated messages for the other fields:

![Image](https://user-images.githubusercontent.com/22962348/193349404-7f58d7ab-664c-4ad6-a592-8b939d09a58d.png)

Would it be possible to replicate the design and function of the native actionkit form here as much as possible?

We can also replicate how actionkit treats the same issue on dark coloured backgrounds, eg.

![Image](https://user-images.githubusercontent.com/22962348/193350000-cae34c0e-bd8a-4e11-acf5-f7d6cd424d22.png)

 ### This will be done when

- [x] Required field validation messages appear directly below the missing fields
- [x] They are highlighted with an orange dot and highlighting
- [x] This highlighting is visible on dark coloured backgrounds

**Comment by sukhada** [comment]
@rezziemaven I looked into this a bit more and it looks like the styles on embedded AK forms are affected by this JS file: www.tfaforms.com/wForms/3.11/js/wforms.js, any idea which plugin this is, and whether we can disable it on AK embed pages?

**Comment by rezziemaven** [comment]
Hi @sukhada! I apologise for the delay in responding to this one! This script is being used to power the Form Assembly form we use on https://350.org/media. Because I had to add it to the `<head>` tag under `Settings > Custom Code`, it unfortunately appears on all pages rather than just this one media page. 

The ideal thing would be to only load this script in the head tag when the url location is equal to https://350.org/media. Perhaps we can move this to the Baseline code in the `header.php` file where it would be easier to do this apart from installing a plugin that would do this. Would you be up for taking this on and creating a new fix branch with this and making a merge request to master?

**Comment by sukhada** [comment]
opened a merge request here: https://gitlab.com/350/web-tools/baseline/-/merge_requests/58!

**Comment by rachelhbd** [comment]
Thanks both, I see the merge request went in! I republished the example wordpress page but am still seeing similar validation behaviour at the moment

**Comment by sukhada** [comment]
@rachelhbd It's possible that the old code is still cached for you? Can you try opening it in an incognito window? This is what I'm seeing on my end: 
<img width="727" alt="Screen Shot 2022-10-21 at 2 22 22 PM" src="https://user-images.githubusercontent.com/1696078/197290742-39cc0404-645c-4b66-b4f0-14099322efd5.png">

**Comment by sukhada** [comment]
@rachelhbd I think before these changes will be reflected we will have to remove the code from `Settings > Custom Code`. @rezziemaven would you be able to do that?

**Comment by rachelhbd** [comment]
Thanks both, this looks great to me now on https://350.org/rachel-test-petition-embed/ using both dark and light backgrounds, so calling this done!

**Comment by rachelhbd** [comment]
@sukhada are there any updates we need to make on ActionKit's side as well for this one? I see the form embedded in https://350.org/rachel-test-petition-embed/ is using the Oct 22 templateset

If so, let's include in the October release

**Comment by rachelhbd** [comment]
Hey @sukhada! I noticed that when the AK page embedded in https://350.org/rachel-test-petition-embed/ is using the October templateset the validated opt-ins look like this: 

![Image](https://user-images.githubusercontent.com/22962348/202849592-e6dd671e-cb6a-406d-ab9d-2839c55f8261.png)

And when the page is using Develop it has a slight layout issue:

![Image](https://user-images.githubusercontent.com/22962348/202849451-8c0c8e48-ad24-4020-9a4d-4c6e89723a35.png)

Not a deal breaker but just wanted to check there wasn't a typo or unclosed tag that might be causing that

**Comment by sukhada** [comment]
@rachelhbd there shouldn't be! i noticed this too, but i think it might just be an embed quirk?

**Comment by rachelhbd** [comment]
Hey hey, hmm the thing is that both versions I'm looking at are embedded pages

So https://350.org/rachel-test-petition-embed/ WP page embeds https://act.350.org/sign/rachel-test-petition/ which uses Develop (and has that slightly off layout for the opt-in validation)

https://350.org/rachel-test-petition-feature-qa/ WP page embeds https://act.350.org/sign/rachel-test-petition-feature-qa/ which is a copy of the same page using the October templateset (and has the right formatting for the validation)

It's not a major one but makes me thing there may have been something small missing missing in the merge process, or an update to the css 

I don't want to block the October release though so okay to go ahead if you and @cjmabry are happy, and we can check what the result is in prod when all the css is updated there

**Comment by cjmabry** [comment]
Looking at this, @sukhada @rachelhbd I think we should at least determine cause before moving on here.

**Comment by cjmabry** [comment]
@sukhada it looks like the `.ak-error` class is being applied to the label rather than the ul item after it in Rache's example.

**Comment by cjmabry** [comment]
It looks like `<label for="privacy_optout" class=" ak-error">No, sorry.</label>` is possibly getting `inline-block` applied on the incorrect page, but I'm not sure from where.

**Comment by sukhada** [comment]
@cjmabry I'm seeing `display:inline-block` on that `label` in both pages

**Comment by cjmabry** [comment]
@sukhada here's what I'm seeing when comparing "Computed" styles:

![Screenshot from 2022-11-21 15-38-23](https://user-images.githubusercontent.com/3048335/203163371-5a5b2f56-9d4e-48ac-b01e-adedcdbf4829.png)
![Screenshot from 2022-11-21 15-38-30](https://user-images.githubusercontent.com/3048335/203163375-c9d3243a-b2be-4762-95f2-f20b59c4395a.png)

**Comment by sukhada** [comment]
This is what I see: 
![Screen Shot 2022-11-21 at 1 40 58 PM](https://user-images.githubusercontent.com/1696078/203163702-5d5388af-f293-4e13-bc32-2478ceb10ffb.png)
![Screen Shot 2022-11-21 at 1 41 11 PM](https://user-images.githubusercontent.com/1696078/203163705-cacc64b9-f903-4915-8f45-28eb5684a157.png)

Does changing the class to "display: inline-block" fix the issue?

**Comment by cjmabry** [comment]
@sukhada it doesn't, but it's the only different I can spot. The "computed" tab should show what the browser is actually using, though, so I'm thinking the issue might be close to that.

**Comment by cjmabry** [comment]
Removing that label in dev tools fixes the issue, so I'm suspecting it's something to do with that label.

**Comment by cjmabry** [comment]
@sukhada okay it looks like it's because `input-radio` is getting `display: flex` and the correct one is not.

**Comment by cjmabry** [comment]
@rachelhbd this should be fixed

**Comment by rachelhbd** [comment]
Yep @cjmabry looks good - thanks for tracking this one down!
