### ISSUE TITLE
Add a countdown to contribution pages

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#398]
User story
-
As a digital fundraiser I'd like to be able to optionally show a countdown on contribution pages, so that when approaching a fundraising deadline I can increase the donor sense of urgency with the hypothesis that this will increase conversion rates

Context
- 
Based on the success of showing a countdown on the homepage banner eg. 
![Image](https://user-images.githubusercontent.com/22962348/193567198-ad50ea73-d504-4846-b5b8-8b0c730ca9e0.png)
Maria and Bianca would like to be able to show a similar countdown on contribution pages for use for donate pages linking through from the banner or mailings at key fundraising moments

I looked at a very MVP design of adding the countdown into the intro text of the page, eg. 
https://act.350.org/donate/web_join_redirect_rachel_test/
But not sure this works visually

![Image](https://user-images.githubusercontent.com/22962348/193574669-b109b7b2-b1c4-4f03-9e5e-9c7f91c6497d.png)

Would it be possible to develop a few design iterations based on v7 for options for positioning and styling of the countdown? https://www.figma.com/proto/9o0tUU1krckXCBLzxjozB0/350-Donation-Accessibility-Ideation?node-id=502%3A139&viewport=3311%2C-1900%2C0.28&scaling=scale-down&page-id=0%3A1%3Ffuid%3D923664738342119661

**Comment by cjmabry** [comment]
@rachelhbd what do you think of these? These borrow some conventions from rest of site, including orange background to draw the eye:

- Desktop: https://www.figma.com/proto/P0Lz1xDEYdM4YGlxT7jWJ9/350-October-2022-Sprint?node-id=801%3A7&viewport=-3391%2C-7419%2C1&scaling=scale-down&page-id=0%3A1%3Ffuid%3D923664738342119661
- Mobile: https://www.figma.com/proto/P0Lz1xDEYdM4YGlxT7jWJ9/350-October-2022-Sprint?node-id=602%3A17&viewport=1542%2C564%2C1&scaling=scale-down&page-id=602%3A15%3Ffuid%3D923664738342119661

Also cc @sukhada and @alandmih for any feedback.

**Comment by rachelhbd** [comment]
Thanks @cjmabry! I got feedback from Maria and Bianca - looks good and the orange works, we are just not sure about the positioning. Sorry that probably my mockup led you in that direction, that was just the easiest place I could put it using the admin!

Would it be possible to see another couple of options? eg. 

- Replacing the "Support 350.org" pre-header
- On the RHS above the donate form
- Sat on top of or just within the blue box, with the orange section spanning the full width of the blue box

I think both would have possibilities for desktop and mobile, so up to you whether to look at desktop first or both together

I think it _might_ also look better if the orange background was a bit tighter with less padding above and below - the size of the orange section just feels a wee a bit much? If that makes it too tight around the countdown highlight, we could perhaps just have the countdown in black with no highlight

And maybe the text could be a bit smaller (particularly so we could aim to keep it on one line where possible, also by shortening the text)

**Comment by cjmabry** [comment]
Hi @rachelhbd, that all sounds good! Will get some more revisions done this week.

**Comment by cjmabry** [comment]
@rachelhbd @mariaroper I've added additional iterations here per your feedback, let me know what your thoughts are:

- Desktop: https://www.figma.com/proto/P0Lz1xDEYdM4YGlxT7jWJ9/350-October-2022-Sprint?node-id=801%3A7&viewport=173%2C545%2C0.32&scaling=scale-down&page-id=0%3A1&starting-point-node-id=801%3A7
- Mobile: https://www.figma.com/proto/P0Lz1xDEYdM4YGlxT7jWJ9/350-October-2022-Sprint?node-id=602%3A17&viewport=173%2C545%2C0.32&scaling=scale-down&page-id=602%3A15&starting-point-node-id=602%3A17

**Comment by rachelhbd** [comment]
nice, thanks @cjmabry! I personally like the one across the top - think it's visually more balanced. @mariaroper what would you say?
 
Or if we go with the version on the LHS above the "Donate" header, then the "Support 350.org" pre-header should come out, too

**Comment by mariaroper** [comment]
I also like the one across the top the best! I'm checking with Bianca too, will let you know what she says

**Comment by cjmabry** [comment]
Sounds great! Here are links to the winning variant:

Desktop: https://www.figma.com/proto/P0Lz1xDEYdM4YGlxT7jWJ9/350-October-2022-Sprint?node-id=940%3A22&scaling=scale-down&page-id=0%3A1&starting-point-node-id=940%3A22&show-proto-sidebar=1

Mobile: https://www.figma.com/proto/P0Lz1xDEYdM4YGlxT7jWJ9/350-October-2022-Sprint?node-id=940%3A85&scaling=scale-down&page-id=602%3A15&starting-point-node-id=940%3A85&show-proto-sidebar=1

@mariaroper do you want to get Cliff's feedback now? Otherwise will wait for your final approval to consider designs complete.

**Comment by cjmabry** [comment]
@mariaroper @rachelhbd this ticket will cover implementing this fully if the test wins, so will move this one to January.

**Comment by mariaroper** [comment]
Yes! Thanks!

**Comment by cjmabry** [comment]
@sukhada this one also ready to put into next release, let me know if you have questions!

**Comment by sukhada** [comment]
@cjmabry PR to merge this into develop [here](https://github.com/350org/ak_intl_v3/pull/413)!

**Comment by cjmabry** [comment]
@alandmih would you have capacity to code review this this week?

**Comment by rachelhbd** [comment]
This is looking good folks, thank you so much! Adding for our records that it looks like this feature is controlled by these custom page fields:
<img width="1065" alt="Screenshot 2023-03-23 at 16 59 17" src="https://user-images.githubusercontent.com/22962348/227279376-7fdbe9ab-9091-4465-bd24-45074ea3af73.png">
As on this page: https://act.350.org/admin/core/donationpage/17188/change/

@sukhada a question that is non-blocking for release, but more about how we communicate/support this -- is there a specific format that the date and time should be entered in for this field that we can add to the custom page field notes? How does it handle timezones?

**Comment by sukhada** [comment]
@rachelhbd If you click into that box, it allows you to select a date + time using a calendar widget! Let me know if that makes sense/if we need more documentation for this

**Comment by sukhada** [comment]
@rachelhbd I believe it uses the user's local timezone - if you check out https://act.350.org/donate/qa_develop_countdown/ you should see a countdown to midnight on Apr 1st in your timezone?
