### ISSUE TITLE
Facebook and Twitter links are using shortlink format on standard thanks page

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#399]
### User story
- As a digital campaigner, I want to be able to track the results of shares from the Sign > Share/Donate flow
- As a digital campaigner, I want AK-tracked links to use the shortened version so that user-facing links (especially when used in tweets) don't include lots of visible tracking code which could affect share rates or get lost

### Context
**Tracking code:** I can see that in this live page using the Sign > share > donate flow (https://act.350.org/sign/stop-rosebank/), the Facebook share is not passing through the action_id or akid to the button link. Even after the action has been taken by the user, the button link is just `https://act.350.org/share/link?type=fb&page_name=stop-rosebank&action_id=&akid=None`

The same is the case for the Twitter share on the demo share page (https://act.350.org/sign/sukhada-demo-share-page), `https://act.350.org/share/link?type=tw&page_name=sukhada-demo-share-page&action_id=&akid=None`

Looking at the documentation for how share links work (https://github.com/350org/action-tools/issues/43), it looks like there could be two possible ways to generate these links, but both depend on being able to pass through either the akid or the actionid:

> To have users share a page from a link on the page itself, before they've taken an action, give them a clickable link that includes their AKID, if it is known:
> `https://act.350.org/share/link?type=TYPE&page={{page.name}}&akid={{user.akid}}&short=1`
> To share after the user has taken an action, such as on a thanks page, you can include the action ID and omit the page and AKID parameters:
> `https://act.350.org/share/link?type=TYPE&action_id={{action.id}}&short=1`

As another example, after signing this test page https://act.350.org/sign/stop-jackdaw-gas-field-uk_RH_test/ 
which is set up to generate a standard thanks page, the url includes akid and action_id `https://act.350.org/cms/thanks/stop-jackdaw-gas-field-uk_RH_test?action_id=26067456&akid=.2483206.ZpvPZ4&ar=1&rd=1&success=1`
and when clicking on the FB and TW share buttons, the akid and action_id are also carried through

**Shortlinks:** Building on https://github.com/350org/action-tools/issues/43, we learned that by adding `&short=1` onto the end of any built-in twitter, facebook or link shares, we can offer users neater share links that should increase share rate and tracking accuracy. It seems like this should be our standard approach across standard thanks pages and Sign > share/donate options.

**Link share on standard thanks page:** We'd also like user-copied share link on standard thanks page ([eg.](https://act.350.org/cms/thanks/stop-jackdaw-gas-field-uk_RH_test?action_id=26067456&akid=.2483206.ZpvPZ4&ar=1&rd=1&success=1)) to include tracking code. The link would be generated by `https://act.350.org/share/link?type=ot&action_id={{action.id}}&short=1`, but it's the resulting shortlink that we'd want the user to copy, eg. `https://act.350.org/share/link?type=ot&action_id=26067456&short=1` when shared in the browser becomes `https://act.350.org/s/2233131.g2veXM`
This is the same logic as we're looking at in #369 

### This will be done when
- [ ] Facebook and Twitter links in the Sign > Donate/Share flow are passing through akid or actionid to enable share tracking
- [ ] Facebook and Twitter links are using shortlink format eg. `&short=1` as standard for share links in the Sign > Donate/Share flow
- [x] Facebook and Twitter links are using shortlink format eg. `&short=1` for share links on the standard thanks pages eg. https://act.350.org/thanks/stop-jackdaw-gas-field-uk_RH_test/ 
- [ ] User-copied share link on standard thanks page are trackable shortlinks

Out of scope - Whatsapp shares seem more complex so that's broken out for scoping here: https://github.com/350org/ak_intl_v3/issues/400

**Comment by rachelhbd** [comment]
hey @sukhada what's the status of this one? I can't remember if it was you or I who changed the status to "ready for QA", but I created a test page with the Oct templateset [](https://act.350.org/sign/sukhada-demo-share-page_oct22/) and I don't think I'm seeing the changes here

**Comment by sukhada** [comment]
@rachelhbd looks like the sync failed for this file, so I force pushed the changes and it should be ready to QA -- sorry about that!

**Comment by rachelhbd** [comment]
Alright, so when looking at this page https://act.350.org/sign/sukhada-demo-share-page_oct22/...

I'm seeing the FB share url work, with the short link (although it does take a few seconds to load for me, that might be unavoidable?): https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fact.350.org%2Fs%2F2250272.gtF4iv

The TW url appears correct when you hover over it, but then loads as a long url in the browser without the akid info: https://twitter.com/intent/tweet?url=https%3A%2F%2Fact.350.org%2Fsign%2Fsukhada-demo-share-page%2F&text=Here%27s+an+example+tweet+%23demo+%23afteractions+  -- is it work asking AK if they have any advice for us on this?

On the standard thanks page example, both TW and FB are loading the shortlink so that's great! I've checked that off above
FB: https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fact.350.org%2Fs%2F2250289.SMVYmA
TW: https://twitter.com/intent/tweet?url=https%3A%2F%2Fact.350.org%2Fs%2F2250290.yxmJQ7&text=Stop+the+Jackdaw+gas+field%21+%23StopJackdaw

And for the last criteria for "user copied share links on the standard thanks page", I actually meant this one - but realising I should have been more specific!
![Image](https://user-images.githubusercontent.com/22962348/200669266-a36ee3b8-d730-4db1-bbff-ac1986e4a0fe.png)

Let's roll this one into the November sprint for finalising and more testing?

**Comment by rachelhbd** [comment]
@sukhada I noticed this is included in the October release which is all good actually, there aren't any bugs being introduced here, just I don't think we've quite got 100% of the way

We can roll the two parts I'm not sure we've landed (the TW share in the flow, and the user copied share links on the thanks page) into the next sprint? Unless I'm missing something or there's a sync error on the TW share?

**Comment by rachelhbd** [comment]
Thanks great! We can triple check with AK for the next iteration - I think that maybe the only piece we'd be missing then would be how many new users join from seeing that particular social share (I think that's what the encoded link allows). This is good for though

**Comment by rachelhbd** [comment]
I've updated the title of this ticket to reflect what we've completed so far

The rest of the acceptance criteria could do with more research and breaking out so we can track new users from their source shares, probably in 2023 - fyi @cjmabry

**Comment by rachelhbd** [comment]
Looks good in Develop in preview mode!
