### ISSUE TITLE
Complete production implementation and QA of ecommerce templateset updates

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#403]
Code updates have now been deployed to the main and affiliate templatesets, so the next steps are
- [x] Alan to update GTM trigger conditions to accept events originating from [act.350.org](http://act.350.org/)
- [x] Alan to put together some QA notes
- [x] QA - likely Julia and/or Rachel
- [ ] By 21 October, evaluate initial data to check it's as expected and see if there are any insights that can inform priorities for the November sprint

Let's set a target to get this done in the next week so that we can collect data throughout the rest of the month of October?

Also for ref: [Documentation work in progress](https://docs.google.com/document/d/1TLpbbeKuIIUgJTSrrHnoSZEQezG2_gEqRBqyYlfTYMY/edit?usp=sharing)

**Comment by juliao762** [comment]
Point 1&2 by the end of Oct 5th
Point 3 by Oct 11th

**Comment by alandmih** [comment]
## Review & QA Notes
### Google Tag Manager Configuration Review
- Visit GTM https://tagmanager.google.com/#/container/accounts/4702514756/containers/13424695/workspaces/130/folders
- Review “Ecommerce - development (archived)” folder. Confirm any Tags (2) are paused
- Review “Ecommerce” folder. Confirm the 5 Event Tags are associated with their accompanying Triggers. Confirm the Pageview - Product Details Tag is associated with the “product details pageview” Trigger

### Analysis and Live Preview
- Visit GTM https://tagmanager.google.com/#/container/accounts/4702514756/containers/13424695/workspaces/130
- Click “Preview” button in top right of Admin Dashboard
- A new tab should open with Google Tag Assistant. A popup will prompt you for a URL to preview.
- Enter any valid AK donation page URL (EG: https://act.350.org/donate/web_join_redirect) and click Connect
- The donation page should open in a new tab
- On the Tag Assistant (GTA) window, press “Continue”
- Step through the donation flow and pause at the following steps to confirm that Tags are being fired as expected. Expected corresponding event in (parentheses)

1. (impression) Whenever a donation “ask” is presented in the frontend, an ”GA - Event - impression” Tag is triggered
2. (DOM Ready) Once the donation page has loaded, a “GA - Pageview - Product Details” Tag is triggered
3. (addToCart) Enter or click a donation amount, click Continue. Confirm “GA - Event - Add Cart” is triggered. Note: Either One-time or Monthly donation can be selected and should trigger the same event.
4. (checkout) Add Address info, click Continue. Confirm “GA - Event - Checkout” is triggered. Inspect Data Layer in GTA by clicking the checkout event and selecting the “Data Layer” tab. Look for “ecommerce.checkout.actionfield”. Confirm “step”=1
5. (checkout) Add credit card or Paypal Payment info, click Continue. “Confirm GA - Event - Checkout” is triggered. Inspect Data Layer in GTA by clicking the checkout event and selecting the “Data Layer” tab. Look for “ecommerce.checkout.actionfield”. Confirm “step”=2.
6. (impression) You should now be on the Thanks page. If there are additional donation asks here, confirm Impressions Tags are being triggered (similar to step 1).
7. (transaction) Confirm “GA - Event - Transaction” Tag has been triggered
8. Repeat the above steps for available variants for donation options. These may include: preset donation values vs custom value, one-time vs monthly frequency, credit card vs Paypal payment option; other currencies 

**Note - Events may also be monitored in realtime via Google Analytics.**
1. Visit https://analytics.google.com/analytics/web/#/realtime/rt-event/a4147446w7993349p257453087/
    a. note: if this direct link does not work, the navigation path is https://analytics.google.com/, select 350.org (Account) -> http://350.org/ (Properties & Apps) -> [WTR] Donations (Views), Realtime (in Reports menu) -> Events 
3. Select “Events (Last 30 min)” filter above the main table
4. You should see the events you are triggering via your testing here. Further filter this table by clicking on an “Enhanced Ecommerce” Event Category entry in the table. All Events in this process aside from Pageview are under this category

**Comment by juliao762** [comment]
**Google Tag Manager Configuration Review**

- [ ] Visit GTM https://tagmanager.google.com/#/container/accounts/4702514756/containers/13424695/workspaces/130/folders

- [ ] Review “Ecommerce - development (archived)” folder. Confirm any Tags (2) are paused

- [ ] Review “Ecommerce” folder. Confirm the 5 Event Tags are associated with their accompanying Triggers. Confirm the Pageview - Product Details Tag is associated with the “product details pageview” Trigger

**Analysis and Live Preview**

- [ ] Visit GTM https://tagmanager.google.com/#/container/accounts/4702514756/containers/13424695/workspaces/130

- [ ] Click “Preview” button in top right of Admin Dashboard

- [ ] A new tab should open with Google Tag Assistant. A popup will prompt you for a URL to preview.

- [ ] Enter any valid AK donation page URL (EG: https://act.350.org/donate/web_join_redirect) and click Connect

- [ ] The donation page should open in a new tab

- [ ] On the Tag Assistant (GTA) window, press “Continue”

- [ ] Step through the donation flow and pause at the following steps to confirm that Tags are being fired as expected. Expected corresponding event in (parentheses)

- [ ] (impression) Whenever a donation “ask” is presented in the frontend, an ”GA - Event - impression” Tag is triggered

- [ ] (DOM Ready) Once the donation page has loaded, a “GA - Pageview - Product Details” Tag is triggered

- [ ] (addToCart) Enter or click a donation amount, click Continue. Confirm “GA - Event - Add Cart” is triggered. Note: Either One-time or Monthly donation can be selected and should trigger the same event.

- [ ] (checkout) Add Address info, click Continue. Confirm “GA - Event - Checkout” is triggered. Inspect Data Layer in GTA by clicking the checkout event and selecting the “Data Layer” tab. Look for “ecommerce.checkout.actionfield”. Confirm “step”=1

- [ ] (checkout) Add credit card or Paypal Payment info, click Continue. “Confirm GA - Event - Checkout” is triggered. Inspect Data Layer in GTA by clicking the checkout event and selecting the “Data Layer” tab. Look for “ecommerce.checkout.actionfield”. Confirm “step”=2.

- [ ] (impression) You should now be on the Thanks page. If there are additional donation asks here, confirm Impressions Tags are being triggered (similar to step 1).

- [ ] (transaction) Confirm “GA - Event - Transaction” Tag has been triggered

Repeat the above steps for available variants for donation options. These may include:

- [ ]  preset donation values vs custom value 
- [ ] one-time vs monthly 
- [ ] frequency, credit card vs Paypal payment option
- [ ] other currencies

**Note - Events may also be monitored in realtime via Google Analytics.**

Visit https://analytics.google.com/analytics/web/#/realtime/rt-event/a4147446w7993349p257453087/

- [ ] a. note: if this direct link does not work, the navigation path is https://analytics.google.com/, select 350.org (Account) -> http://350.org/ (Properties & Apps) -> [WTR] Donations (Views), Realtime (in Reports menu) -> Events

- [ ] Select “Events (Last 30 min)” filter above the main table

- [ ] You should see the events you are triggering via your testing here. Further filter this table by clicking on an “Enhanced Ecommerce” Event Category entry in the table. All Events in this process aside from Pageview are under this category

**Comment by juliao762** [comment]
Hey @alandmih I have done [the QA process ](https://docs.google.com/document/d/1ILO-J6RSQUbG-4lHmbStRFDBCPJJDqB8vfdRLxfLEuE/edit)and there are few points:

- the number of tags in folders don't match (there is 1 in the archived, 6 in the final one)
- I can't make sense out of how product impressions are loaded (I think way to many?)
- Side question: do you know why is there so many (in hundreds) optimize.domChange events? It makes the QA process very difficult and doesn't seem right. I wrote some notes of what I have observed. 

The rest looks fine to me!


Note: I have entered each time 350.org homepage as a page to preview and navigated to 2 different donation form from the homepage.

**Comment by juliao762** [comment]
Hey @alandmih! 
I think by a chance I have ended up doing some reverse QA on this project. I have a suspicion that we might be overcounting transactions / events actions = transactions on non-donation pages.

I wanted to explore where we ended up recording transactions [on this experiment ](https://optimize.google.com/optimize/home/#/accounts/4703227587/containers/13447940/experiments/247/report):

![image](https://user-images.githubusercontent.com/80909087/197580556-54c44192-1a42-48dd-9b13-d6e3a83f127b.png)

I ended up building a simple report in Data Studio to show me what event labels recorded transactions (so Enhanced Ecommerce Category, event Action = transaction) for this particular experiment. 

What I ended up with was a list of donation and non donation action pages which recorded transactions:

![image](https://user-images.githubusercontent.com/80909087/197580879-109c377c-6b74-49c7-a996-9d9fec695239.png)

Link: https://datastudio.google.com/reporting/fb298355-8d01-454e-8a70-a1d2ab5700a7/page/p_rwzmg2uwzc/edit

**Comment by juliao762** [comment]
I have just signed up this form: https://act.350.org/signup/eacop-week

 and I see in fact that the GA Transaction event fires up:

![image](https://user-images.githubusercontent.com/80909087/197581523-22fe35f4-c300-49e9-93e3-64397621a8b1.png)

**Comment by juliao762** [comment]
Maybe the referrer should be more strict and include only donation pages?

So: https://act.350.org/donate/

![image](https://user-images.githubusercontent.com/80909087/197583109-5d04f2e6-f351-4142-bac3-33bf6bf33295.png)

**Comment by juliao762** [comment]
![image](https://user-images.githubusercontent.com/80909087/197583277-abb35376-8a44-4125-8939-0840b649a06c.png)

**Comment by alandmih** [comment]
> Maybe the referrer should be more strict and include only donation pages?
> 
> So referrer starts with: https://act.350.org/donate

This would be effective for most cases, but an unfortunate issue with relying on the referrer value is that certain browsers - i think it was safari mainly - only respect the domain as the referrer, and discards of the rest of the path for that value.

**Comment by alandmih** [comment]
> Could you please check what is causing the problem here?



> Maybe the referrer should be more strict and include only donation pages?
> 
> So referrer starts with: https://act.350.org/donate

The current templateset essentially assumes that if you land on the Thanks page when coming from act.350.org, you've completed a donation transaction. We could set a condition on the tag that checks 
the `Event Label` and only records a donation transaction if the originating form contains `/donate/`. The  transaction from your example has `eventLabel: "/signup/eacop-week"` which would get filtered out by such a condition.

**Comment by juliao762** [comment]
Thanks for explaining! Would you add the changes to the triggers? (I would prefer to leave this to you at this point).

**Comment by alandmih** [comment]
> Thanks for explaining, @alandmih ! Would you add the changes to the triggers? (I would prefer to leave this to you at this point).

@juliao762 I will add this today + do a bit of validation and report back here once done!

**Comment by alandmih** [comment]
Hi @juliao762 I updated the triggers and it appears to be working properly. However, I think there is actually a better way to handle this within the templateset thanks.html itself. I believe we can utilize the actionkit template tag `{{ action.page.type }}` to check if the action was a donation, and conditionally fire the transaction event itself based on that condition. In case you are curious, here is a [list of the action page types](https://docs.actionkit.com/docs/manual/api/pages.html).

I've left the simple modification to the triggers in GTM - not published. We can either push those to production for now, or we can hold off until we add and QA adding an `{{ action.page.type }} == "donation"` condition inside the thanks page. Just let me know your preference and I can proceed accordingly!

Here's a simple validation of the GTM trigger update being properly not-fired on the signup page, but fired on a donation page: 
![ua-signup-donation_label](https://user-images.githubusercontent.com/6234322/198292815-e006da3a-ea9f-44e7-8ea0-d92ef92d49de.png)
![ua-donation-donation_label](https://user-images.githubusercontent.com/6234322/198292821-de2ab8ad-c969-451b-a87e-8852df98be9a.png)

**Comment by juliao762** [comment]
@alandmih did you restrict the pages to trigger the events only on donation pages?
This is the data I pulled about check out (from 5th of Nov) and I still the ecommerce events triggered on non-donation pages:

![image](https://user-images.githubusercontent.com/80909087/200580473-bd12d746-eba6-435a-849d-314855661fc6.png)

**Comment by juliao762** [comment]
Hey @alandmih, I think I prefer to handle this within the templateset thanks.html itself. 

Do you think I should go ahead with the changes in GTM anyway?

**Comment by juliao762** [comment]
hey @alandmih regarding DOM change keep loading, it is connected to running an experiment on Google Optimize, I just checked it today on 350.org/get-involved where we have a running experiment: 
![image](https://user-images.githubusercontent.com/80909087/203104092-e62233ca-d602-4ab4-8949-85dba35d6ad1.png)

**Comment by alandmih** [comment]
> hey @alandmih regarding DOM change keep loading, it is connected to running an experiment on Google Optimize, I just checked it today on 350.org/get-involved where we have a running experiment: 

-makes sense, thanks for investigating! Should we end that experiment or is there still useful info to gather from it?

Also @juliao762, do you think there are any other issues to address here now that the "restrict transaction events to donation pages only" code has been added, before we can close this ticket out? Perhaps one item to follow up on is [this one](https://github.com/350org/ak_intl_v3/issues/403#issuecomment-1307264503). We can make separate a ticket for that specifically if it is still an issue.

**Comment by cjmabry** [comment]
Hi @juliao762 and @alandmih, was this all wrapped up and could I close out this ticket or were we still waiting on things?

**Comment by juliao762** [comment]
You can close it, thank you @cjmabry !
