### ISSUE TITLE
Draft import checklist

### ISSUE THREAD

**Issue by juliao762** [350org/ak_intl_v3#410]
Goal: we have a checklist that specifies how to fill out following parts when creating an import page:

- Page titles
- Page notes
- Default action source
- Privacy notes

**Comment by juliao762** [comment]
@jaseinvt letting you know that I put this in

**Comment by juliao762** [comment]
Draft of the checklist: https://docs.google.com/document/d/1sRF778WKp8oN8KItNLl5S5_6NjQAWqHe3RY1HS_pimw/edit#heading=h.2zzrgdpmt32k

**Comment by juliao762** [comment]
@jaseinvt do you have any other comments to add about the checklist itself? If not, I would like to mark it as done.

**Comment by rachelhbd** [comment]
I changed the status to "ready for feedback", for now :)
