### ISSUE TITLE
[Help Desk Request] Link to update donor information is not working

### ISSUE THREAD

**Issue by cjmabry** [350org/ak_intl_v3#411]
*Request Form* submission from 
[@Carly Brownell](https://withtheranks.slack.com/team/U015DEN036D)
*What do you need help with?*
Hi team!
I think there is something wrong with the Update page. When I send donors www.350.org/update or 350.org/update (both of which have worked in the past), the links do not work. Also, I have heard from multiple donors that the link we send in our automatic emails telling donors to update their monthly donations (http://act.350.org/go/3105?t=3&utm_medium=email&akid=225511%2E518020%2EyHrqRy) does not work either. Right now, the only way that I can get the correct link to our Update page is by going to our donation page and clicking the option at the bottom to Update Your Account: https://350.org/update?_ga=2.67553746.2104891870.1670255527-1387178509.1657138734
*Link to problem page or example*
350.org/update
*How urgent is your request*
Normal
*Do you know what team the request is for?*
*What is the estimated deadline?*

**Comment by cjmabry** [comment]
From @sukhada:

> [www.350.org/update](http://www.350.org/update) should redirect to [350.org/update](http://350.org/update) and then [act.350.org/me](http://act.350.org/me)
[5:07 PM](https://withtheranks.slack.com/archives/C025QGH1V8U/p1670281631885019)
looks like it’s set up as a wordpress redirect regex: https://threefiftystag.wpengine.com/wp-admin/tools.php?page=redirection.php&filterby%5Burl%5D=update
[5:09 PM](https://withtheranks.slack.com/archives/C025QGH1V8U/p1670281748153279)
i think this is just an issue with [www.350.org](http://www.350.org/) not redirecting to [350.org](http://350.org/)
[5:09 PM](https://withtheranks.slack.com/archives/C025QGH1V8U/p1670281764177009)
the setting can be updated here: https://threefiftystag.wpengine.com/wp-admin/tools.php?page=redirection.php&sub=site under Canonical Settings

**Comment by rachelhbd** [comment]
Thanks @cjmabry! This sounds right - I think it'd be best to manage redirects in the main site, not sure what would happen if we tried to manage them in staging

We can update the link used in mailings, but maybe easier just to make sure the redirect includes that path or add a new one to cover www.

**Comment by cjmabry** [comment]
This does appear to be an issue with the www subdomain. Sending users directly to https://350.org/update (without www) does appear to be working.

- www.350.org is not configured properly to serve the 350 website or handle redirects. This whole subdomain does not work, and we should investgate where these DNS settings are configured as this is likelier a bigger issue and we should work to get this subdomain working as it will be a commonly typed path to the 350 website from users 
- http://act.350.org/go/3105?t=3&utm_medium=email&akid=225511%2E518020%2EyHrqRy actually redirects to the www subdomain.

**Recommended next steps:**
- Instruct users to refer people to the non-www site for now (i.e. 350.org/update)
- Investigate if we can change act.350.org URL above that is at the bottom of emails to redirect to the non-www website (@mariaroper do you know if this is possible?)
- Gain access to wherever 350.org's DNS configuration is managed and investigate why the www subdomain is failing. ( @rachelhbd or @rezziemaven would you know where this is managed?)

**Comment by rezziemaven** [comment]
Hey @cjmabry; the www subdomain is managed in CloudFlare. Do you already have access to this?

**Comment by cjmabry** [comment]
Following up here, I let Carly know this should have been fixed in December, and will open back up if there are any remaining issues.

cc @rezziemaven
