### ISSUE TITLE
On the event search page on mobile, hide the event description from the events search results

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#432]
Related to #431 

### Goal, user story, and/or definition of the problem
As a user searching for events near me, I'd like to be able to see more events for less scrolling

### Additional context
On the event search page for the Canada campaign, we see how many events have long descriptions (highlighted in purple below) that require scrolling and can be quite repetitive
![Image](https://github.com/350org/ak_intl_v3/assets/22962348/9b9203c6-3e81-4591-a137-048e77b66902)

I think it would be better to hide these on mobile and allow people to click through to the event registration page to view the full descriptions

Live AK search page example https://act.350.org/event/canada-burning-doa/search/
And a non-live test search page is at https://act.350.org/event/demo-event-campaign/search/

### This will be done when
- [x] Event descriptions are only shown in the event search results on desktop, and hidden on mobile 

### People needed
WTR/Sukhada

**Comment by sukhada** [comment]
@rachelhbd did we want to do this specifically for this campaign?

**Comment by rachelhbd** [comment]
Thanks for checking @sukhada, all campaigns please!
