### ISSUE TITLE
by end July: Hide Paypal as an option on donate forms if currency is ZAR

### ISSUE THREAD

**Issue by rachelhbd** [350org/ak_intl_v3#435]
### Goal, user story, and/or definition of the problem
We're hoping to soon be adding South African Rand (ZAR) as an option on our donate forms, however it's not an accepted currency by Paypal
Before we go ahead and activate the currency so it appears on the dropdown, we'd like to make sure that Paypal won't appear as an option on step 3

### Additional context
We would like to activate ZAR by 28 July latest, so this one is a bit timely
And because we won't have ZAR as an available option, so if you want to try this out it might be easier to test this with another currency - perhaps BRL because we don't really fundraise in Brazil currently

### This will be done when
If donate form currency = ZAR (or if ZAR has been chosen in the dropdown or identified by url parameter ?currency=ZAR), the Paypal option on step will not display

### People needed
@sukhada does this sound doable?

**Comment by sukhada** [comment]
@rachelhbd I've added the code changes to the [July 23 templateset](https://act.350.org/admin/cms/templateset/556/templates). Currently it's set to work with BRL as you mentioned - let me know if it's working as expected and I can update to use ZAR instead.

**Comment by rachelhbd** [comment]
yes that looks great, thank you!

**Comment by rachelhbd** [comment]
@sukhada when do you think would be feasible to go live with this one?

**Comment by sukhada** [comment]
I was thinking this can go out with the sign share donate changes, if that works? will aim to get them both out by EOW!

**Comment by rachelhbd** [comment]
yep sounds great - thanks!
