### ISSUE TITLE
Implement local photo for Canada banner

### ISSUE THREAD

**Issue by cjmabry** [350org/ak_intl_v3#456]

**Comment by cjmabry** [comment]
@sukhada here's ticket for implementing Canda banner, could you add image here?

**Comment by sukhada** [comment]
Image is attached: 
![canada_banner](https://github.com/350org/ak_intl_v3/assets/1696078/6ab9e657-5f44-4220-9098-c18523403f17)

**Comment by cjmabry** [comment]
@sukhada was Maria QAing this or did you have QA notes for this one?
